/**
 * Dynamic Worker orchestration helpers.
 *
 * Provides typed, production-safe wrappers for two Dynamic Worker binding models:
 *
 * **Model A — DYNAMIC_WORKER_LOADER** (string-source loader):
 *   - `dispatchToDynamicWorker()` — ZTA-safe helper using env.DYNAMIC_WORKER_LOADER
 *   - `isDynamicWorkerAvailable()` — feature-flag guard for DYNAMIC_WORKER_LOADER
 *
 * **Model B — LOADER** (DynamicDispatchNamespace):
 *   - `runAstParseInDynamicWorker()` — ephemeral isolate for AST parsing via env.LOADER
 *   - `runValidateInDynamicWorker()` — ephemeral isolate for rule validation via env.LOADER
 *   - `getOrCreateUserAgent()` — persistent per-user AI agent Worker via env.LOADER.get()
 *
 * All ephemeral Workers are created with `globalOutbound: null` (zero network
 * access) because AST parsing and rule validation are pure transforms.
 *
 * @see https://developers.cloudflare.com/dynamic-workers/
 * @see https://github.com/jaypatrick/adblock-compiler/issues/1386
 */

import type { DynamicWorkerSafeBindings, Env } from '../types.ts';
import type { DynamicAstParseOptions, DynamicValidateOptions, DynamicWorkerResult, DynamicWorkerTask } from './types.ts';
import { isLoaderAvailable, makeAgentWorkerId } from './types.ts';

// ============================================================================
// Constants (DYNAMIC_WORKER_LOADER model)
// ============================================================================

/** Content-Type used for all inter-Worker task POST requests. */
const TASK_CONTENT_TYPE = 'application/json';

/** Internal URL used as the request target inside the dynamic Worker isolate. */
const INTERNAL_TASK_URL = 'https://internal.dynamic-worker/task';

// ============================================================================
// Public API — Model A: DYNAMIC_WORKER_LOADER
// ============================================================================

/**
 * Dispatches a structured task to a freshly spawned Dynamic Worker.
 *
 * @param env    - Caller's Worker environment (must have DYNAMIC_WORKER_LOADER bound)
 * @param source - ES module source string for the dynamic Worker
 * @param task   - Typed task descriptor
 * @returns Parsed JSON response body from the dynamic Worker
 *
 * @throws {Error} if DYNAMIC_WORKER_LOADER is not bound (misconfiguration)
 * @throws {Error} if the dynamic Worker returns a non-2xx response
 */
export async function dispatchToDynamicWorker<T = unknown>(
    env: Env,
    source: string,
    task: DynamicWorkerTask,
): Promise<T> {
    if (!env.DYNAMIC_WORKER_LOADER) {
        throw new Error(
            'DYNAMIC_WORKER_LOADER binding is not configured. ' +
                'Add `type = "dynamic_worker_loader"` to wrangler.toml.',
        );
    }

    if (!source.trim()) {
        throw new Error('Dynamic Worker source must be a non-empty string.');
    }

    // Spawn an ephemeral Worker with minimum required bindings only (ZTA).
    const handle = await env.DYNAMIC_WORKER_LOADER.load(source, {
        bindings: {
            COMPILATION_CACHE: env.COMPILATION_CACHE,
            RATE_LIMIT: env.RATE_LIMIT,
            COMPILER_VERSION: env.COMPILER_VERSION,
        },
    });

    const request = new Request(INTERNAL_TASK_URL, {
        method: 'POST',
        headers: { 'Content-Type': TASK_CONTENT_TYPE },
        body: JSON.stringify(task),
    });

    const response = await handle.fetch(request);

    if (!response.ok) {
        const errorText = await response.text();
        throw new Error(
            `Dynamic Worker returned ${response.status}: ${errorText}`,
        );
    }

    return response.json() as Promise<T>;
}

/**
 * Returns true if the DYNAMIC_WORKER_LOADER binding is present in env.
 * Use this to feature-flag dynamic Worker dispatch vs. fallback paths.
 */
export function isDynamicWorkerAvailable(env: Env): boolean {
    return !!env.DYNAMIC_WORKER_LOADER;
}

// ============================================================================
// Private helpers — Model B: LOADER (DynamicDispatchNamespace)
// ============================================================================

/**
 * Returns the bundled source for the AST worker isolate.
 *
 * TODO(#1386): Replace with a build artifact generated by @cloudflare/worker-bundler
 * once the build pipeline is wired up.
 */
function getAstWorkerSource(): string {
    return `
export default {
  async fetch(request) {
    const body = await request.json();
    const { operation, rules = [], text } = body;
    const startTime = Date.now();

    if (operation === 'parse') {
      return Response.json({
        success: true,
        parsedRules: [],
        summary: { total: rules.length ?? 0 },
        executedIn: 'dynamic-worker-isolate',
        duration: \`\${Date.now() - startTime}ms\`,
      });
    }

    if (operation === 'validate') {
      return Response.json({
        success: true,
        valid: true,
        totalRules: rules.length,
        validRules: rules.length,
        invalidRules: 0,
        errors: [],
        warnings: [],
        executedIn: 'dynamic-worker-isolate',
        duration: \`\${Date.now() - startTime}ms\`,
      });
    }

    return Response.json(
      {
        success: false,
        error: 'Unsupported operation',
        executedIn: 'dynamic-worker-isolate',
        duration: \`\${Date.now() - startTime}ms\`,
      },
      { status: 400 },
    );
  },
};
`;
}

/**
 * Returns the bundled source for the per-user AI agent Worker.
 *
 * TODO(#1386): Replace with output of @cloudflare/worker-bundler targeting the
 * agents SDK AiAgent class + tool definitions.
 */
function getAgentWorkerSource(): string {
    return `
export default {
  async fetch(request) {
    return Response.json({
      message: 'Dynamic AI agent stub active',
      userId: new URL(request.url).searchParams.get('userId'),
      note: 'Replace with bundled AiAgent source targeting agents SDK',
      executedIn: 'dynamic-worker-isolate',
    });
  }
};`;
}

/**
 * Extracts a human-readable error message from a non-OK isolate Response.
 * Tries to parse `error` or `message` fields from JSON; falls back to the raw
 * response text, then a generic string.
 */
async function parseIsolateErrorMessage(response: Response): Promise<string> {
    try {
        const maybeJson = await response.json() as Record<string, unknown>;
        if (typeof maybeJson.error === 'string' && maybeJson.error) return maybeJson.error;
        if (typeof maybeJson.message === 'string' && maybeJson.message) return maybeJson.message;
        return JSON.stringify(maybeJson);
    } catch {
        try {
            const text = await response.text();
            if (text) return text;
        } catch { /* fall through */ }
    }
    return 'Dynamic Worker error';
}

// ============================================================================
// Public API — Model B: LOADER (DynamicDispatchNamespace)
// ============================================================================

/**
 * Runs AST parsing inside an ephemeral dynamic Worker isolate via env.LOADER.
 *
 * The isolate has NO network access (`globalOutbound: null`) and NO bindings —
 * it receives only the request body and returns parsed AST data.
 *
 * Falls back to `null` if `env.LOADER` is not configured, allowing the caller
 * to fall back to the existing in-process `handleASTParseRequest()`.
 */
export async function runAstParseInDynamicWorker(
    options: DynamicAstParseOptions,
    env: Env,
): Promise<DynamicWorkerResult | null> {
    if (!isLoaderAvailable(env)) {
        return null;
    }

    const startTime = Date.now();
    try {
        const worker = await env.LOADER!.load({
            compatibilityDate: '2026-01-01',
            mainModule: 'ast-worker.js',
            modules: {
                'ast-worker.js': getAstWorkerSource(),
            },
            globalOutbound: null,
            bindings: {},
        });

        const response = await worker.fetch(
            new Request('https://dynamic-worker/ast', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ operation: 'parse', ...options }),
            }),
        );

        const durationMs = Date.now() - startTime;

        if (!response.ok) {
            const errorMessage = await parseIsolateErrorMessage(response);
            return { success: false, status: response.status, error: errorMessage, durationMs };
        }

        const data = await response.json();
        return { success: true, status: response.status, data, durationMs };
    } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        return { success: false, error: message, durationMs: Date.now() - startTime };
    }
}

/**
 * Runs rule validation inside an ephemeral dynamic Worker isolate via env.LOADER.
 *
 * Same isolation model as `runAstParseInDynamicWorker()`:
 * `globalOutbound: null`, no bindings, pure transform.
 */
export async function runValidateInDynamicWorker(
    options: DynamicValidateOptions,
    env: Env,
): Promise<DynamicWorkerResult | null> {
    if (!isLoaderAvailable(env)) {
        return null;
    }

    const startTime = Date.now();
    try {
        const worker = await env.LOADER!.load({
            compatibilityDate: '2026-01-01',
            mainModule: 'ast-worker.js',
            modules: {
                'ast-worker.js': getAstWorkerSource(),
            },
            globalOutbound: null,
            bindings: {},
        });

        const response = await worker.fetch(
            new Request('https://dynamic-worker/validate', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ operation: 'validate', ...options }),
            }),
        );

        const durationMs = Date.now() - startTime;

        if (!response.ok) {
            const errorMessage = await parseIsolateErrorMessage(response);
            return { success: false, status: response.status, error: errorMessage, durationMs };
        }

        const data = await response.json();
        return { success: true, status: response.status, data, durationMs };
    } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        return { success: false, error: message, durationMs: Date.now() - startTime };
    }
}

/**
 * Gets or creates a persistent dynamic Worker for the given authenticated user via env.LOADER.
 *
 * Returns `null` if `env.LOADER` is not configured (LOADER binding absent).
 *
 * @param userId - The authenticated user's Better Auth user ID.
 * @param request - The incoming HTTP request to dispatch into the agent Worker.
 * @param env - The Worker environment bindings.
 */
export async function getOrCreateUserAgent(
    userId: string,
    request: Request,
    env: Env,
): Promise<Response | null> {
    if (!isLoaderAvailable(env)) {
        return null;
    }

    const workerId = makeAgentWorkerId(userId);

    const agentBindings: DynamicWorkerSafeBindings = {};
    if (env.COMPILATION_CACHE) agentBindings.COMPILATION_CACHE = env.COMPILATION_CACHE;
    if (env.METRICS) agentBindings.METRICS = env.METRICS;

    try {
        const agentWorker = await env.LOADER!.get(
            workerId,
            (_id: string) => ({
                compatibilityDate: '2026-01-01',
                mainModule: 'agent-main.js',
                modules: {
                    // TODO(#1386): Replace with bundled agents SDK AiAgent source once @cloudflare/worker-bundler
                    'agent-main.js': getAgentWorkerSource(),
                },
                globalOutbound: null,
                bindings: agentBindings,
            }),
        );

        return agentWorker.fetch(request);
    } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        // deno-lint-ignore no-console
        console.error(`[DynamicWorkers] Failed to get/create user agent for ${userId}:`, message);
        return null;
    }
}
