/**
 * Dynamic Workers loader utilities.
 *
 * Provides typed, production-safe wrappers around `env.LOADER.load()` and
 * `env.LOADER.get()` for the three primary use cases in this project:
 *
 *   1. `runAstParseInDynamicWorker()` — ephemeral isolate for AST parsing
 *   2. `runValidateInDynamicWorker()` — ephemeral isolate for rule validation
 *   3. `getOrCreateUserAgent()` — persistent per-user AI agent Worker
 *
 * All ephemeral Workers are created with `globalOutbound: null` (zero network
 * access) because AST parsing and rule validation are pure transforms.
 *
 * The per-user agent Workers are persistent (DO-backed hibernation) and are
 * granted only the bindings they need for conversational AI (cache read,
 * metrics write). They do NOT get R2, D1, Queue, or outbound network access
 * by default.
 *
 * @see ideas/CLOUDFLARE_DYNAMIC_WORKERS_PIVOT.md
 * @see https://github.com/jaypatrick/adblock-compiler/issues/1386
 */

import type { Env } from '../types.ts';
import type { DynamicAstParseOptions, DynamicValidateOptions, DynamicWorkerResult } from './types.ts';
import { isLoaderAvailable, makeAgentWorkerId } from './types.ts';

// ---------------------------------------------------------------------------
// Module source — loaded into dynamic Worker isolates at runtime.
// In production, replace this with the output of @cloudflare/worker-bundler.
// ---------------------------------------------------------------------------

/**
 * Returns the bundled source for the AST worker isolate.
 *
 * TODO(#1386): Replace with a build artifact generated by @cloudflare/worker-bundler
 * once the build pipeline is wired up. The bundler should:
 *   1. Bundle `worker/dynamic-workers/ast-worker.ts` + ASTViewerService
 *   2. Emit a single ESM string constant imported here
 *   3. Remove the inline stub below
 *
 * @see https://developers.cloudflare.com/dynamic-workers/worker-bundler/
 */
function getAstWorkerSource(): string {
    // Inline stub — replace with bundled output in production.
    return `
export default {
  async fetch(request) {
    const body = await request.json();
    const { operation, rules = [], text } = body;
    const startTime = Date.now();
    if (operation === 'parse') {
      return Response.json({
        success: true, parsedRules: [], summary: { total: rules.length ?? 0 },
        executedIn: 'dynamic-worker-isolate', durationMs: Date.now() - startTime,
      });
    }
    if (operation === 'validate') {
      return Response.json({
        success: true, valid: true, totalRules: rules.length, validRules: rules.length,
        invalidRules: 0, errors: [], warnings: [], executedIn: 'dynamic-worker-isolate',
        durationMs: Date.now() - startTime,
      });
    }
    return Response.json({ error: 'Unknown operation' }, { status: 400 });
  }
};`;
}

// ---------------------------------------------------------------------------
// Ephemeral Worker helpers
// ---------------------------------------------------------------------------

/**
 * Runs AST parsing inside an ephemeral dynamic Worker isolate.
 *
 * The isolate has NO network access (`globalOutbound: null`) and NO bindings —
 * it receives only the request body and returns parsed AST data.
 *
 * Falls back to `null` if `env.LOADER` is not configured, allowing the caller
 * to fall back to the existing in-process `handleASTParseRequest()`.
 */
export async function runAstParseInDynamicWorker(
    options: DynamicAstParseOptions,
    env: Env,
): Promise<DynamicWorkerResult | null> {
    if (!isLoaderAvailable(env)) {
        // LOADER not configured — caller should fall back to in-process handler
        return null;
    }

    const startTime = Date.now();
    try {
        const worker = await env.LOADER!.load({
            compatibilityDate: '2026-01-01',
            mainModule: 'ast-worker.js',
            modules: {
                'ast-worker.js': getAstWorkerSource(),
            },
            // Zero Trust: pure transform, no network needed
            globalOutbound: null,
            // No bindings: this worker receives only the request body
            bindings: {},
        });

        const response = await worker.fetch(
            new Request('https://dynamic-worker/ast', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ operation: 'parse', ...options }),
            }),
        );

        const data = await response.json();
        return {
            success: response.ok,
            data,
            durationMs: Date.now() - startTime,
        };
    } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        return {
            success: false,
            error: message,
            durationMs: Date.now() - startTime,
        };
    }
}

/**
 * Runs rule validation inside an ephemeral dynamic Worker isolate.
 *
 * Same isolation model as `runAstParseInDynamicWorker()`:
 * `globalOutbound: null`, no bindings, pure transform.
 */
export async function runValidateInDynamicWorker(
    options: DynamicValidateOptions,
    env: Env,
): Promise<DynamicWorkerResult | null> {
    if (!isLoaderAvailable(env)) {
        return null;
    }

    const startTime = Date.now();
    try {
        const worker = await env.LOADER!.load({
            compatibilityDate: '2026-01-01',
            mainModule: 'ast-worker.js',
            modules: {
                'ast-worker.js': getAstWorkerSource(),
            },
            globalOutbound: null,
            bindings: {},
        });

        const response = await worker.fetch(
            new Request('https://dynamic-worker/validate', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ operation: 'validate', ...options }),
            }),
        );

        const data = await response.json();
        return {
            success: response.ok,
            data,
            durationMs: Date.now() - startTime,
        };
    } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        return {
            success: false,
            error: message,
            durationMs: Date.now() - startTime,
        };
    }
}

// ---------------------------------------------------------------------------
// Per-user persistent agent Worker helper
// ---------------------------------------------------------------------------

/**
 * Gets or creates a persistent dynamic Worker for the given authenticated user.
 *
 * The Worker is identified by `agent-{userId}` — a stable name tied to the
 * user's Clerk/BetterAuth ID. It stays warm between requests and hibernates
 * when idle (Durable Object hibernation semantics).
 *
 * Bindings granted:
 *   - `COMPILATION_CACHE` (KV read) — for context-aware compilation suggestions
 *   - `METRICS` (KV write) — for per-agent telemetry
 *   - NO R2, D1, Queue, or outbound network access
 *
 * Returns `null` if `env.LOADER` is not configured (LOADER binding absent).
 *
 * @param userId - The authenticated user's ID (Clerk/BetterAuth userId).
 * @param request - The incoming HTTP request to dispatch into the agent Worker.
 * @param env - The Worker environment bindings.
 *
 * @see ideas/CLOUDFLARE_DYNAMIC_WORKERS_PIVOT.md — Per-user agent model
 */
export async function getOrCreateUserAgent(
    userId: string,
    request: Request,
    env: Env,
): Promise<Response | null> {
    if (!isLoaderAvailable(env)) {
        // LOADER not configured — caller should fall back to existing agent-routing.ts
        return null;
    }

    const workerId = makeAgentWorkerId(userId);

    try {
        const agentWorker = await env.LOADER!.get(
            workerId,
            (_id: string) => ({
                compatibilityDate: '2026-01-01',
                mainModule: 'agent-main.js',
                modules: {
                // TODO(#1386): Replace with bundled ASTViewerService once @cloudflare/worker-bundler
                    'agent-main.js': getAgentWorkerSource(),
                },
                // Agents DO need outbound for LLM API calls — inherit parent outbound.
                // Restrict further once specific LLM service bindings are available.
                globalOutbound: undefined,
                bindings: {
                    // Read access to the compilation cache for context
                    COMPILATION_CACHE: env.COMPILATION_CACHE,
                    // Write access for per-agent metrics
                    METRICS: env.METRICS,
                    // No R2, D1, Queue, or other bindings — principle of least privilege
                },
            }),
        );

        return agentWorker.fetch(request);
    } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        // deno-lint-ignore no-console
        console.error(`[DynamicWorkers] Failed to get/create user agent for ${userId}:`, message);
        return null;
    }
}

/**
 * Returns the bundled source for the per-user AI agent Worker.
 *
 * TODO(#1386): Replace with output of @cloudflare/worker-bundler targeting the
 * agents SDK AiAgent class + tool definitions. The bundled output sidesteps
 * the async_hooks/esbuild incompatibility that currently blocks direct SDK
 * use in the main Worker (see issue #1377).
 */
function getAgentWorkerSource(): string {
    // Minimal stub — replaces with full AiAgent bundle in production.
    return `
export default {
  async fetch(request) {
    return Response.json({
      message: 'Dynamic AI agent stub active',
      userId: new URL(request.url).searchParams.get('userId'),
      note: 'Replace with bundled AiAgent source targeting agents SDK',
      executedIn: 'dynamic-worker-isolate',
    });
  }
};`;
}
