name: adblock-compiler-local
values:
  - key: baseUrl
    value: 'http://localhost:8787'
    enabled: true
  - key: apiKey
    value: 'blq_2086750daf8720ae10feb955a21cb3ecf41194d77d66876a'
    enabled: true
  - key: bearerToken
    value: ''
    enabled: true
  - key: adminKey
    value: ''
    enabled: true
  - key: turnstileToken
    value: 'NEWMAN-BYPASS-TOKEN'
    enabled: true
  - key: paygSessionToken
    value: ''
    enabled: true
