name: bloqr-backend
values:
  - key: baseUrl
    value: 'https://api.bloqr.dev/api'
    enabled: true
  - key: originUrl
    value: 'https://api.bloqr.dev'
    enabled: true
  - key: apiKey
    value: ''
    enabled: true
  - key: bearerToken
    value: ''
    enabled: true
  - key: adminKey
    value: ''
    enabled: true
  - key: turnstileToken
    value: 'NEWMAN-BYPASS-TOKEN'
    enabled: true
  - key: paygSession
    value: ''
    enabled: true
