default_install_hook_types: [pre-push]

repos:
    - repo: https://github.com/rhysd/actionlint
      rev: v1.7.7
      hooks:
          - id: actionlint
            stages: [pre-push]

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.9.0
      hooks:
          - id: ruff
            args: [--fix]
            files: ^tools/.*\.py$
          - id: ruff-format
            files: ^tools/.*\.py$
