$kind: http-request
description: Returns the current version from deployment history
url: {{baseUrl}}/version
method: GET
headers:
  Accept: application/json
  Authorization: Bearer {{apiKey}}
body:
  type: text
  content: ""
examples: ./.resources/Get latest deployment version.resources/examples
order: 1000
