-- D1 Migration: error_events
-- Purpose: Create error_events table for persistent error logging from both
--          the Cloudflare Worker (app.onError) and the Angular frontend
--          (POST /api/log/frontend-error).
--
-- Applied via: wrangler d1 migrations apply adblock-compiler-d1-database
--
-- This table provides a lightweight D1 edge-local audit trail for unhandled
-- errors. It complements Sentry (real-time alerting) with persistent,
-- queryable records that can be analysed offline.
--
-- Fields:
--   id          — UUID v4 primary key (generated by Worker)
--   source      — 'worker' | 'frontend'
--   severity    — 'info' | 'warning' | 'error' | 'fatal' (nullable)
--   message     — Error message text (required)
--   stack       — Stack trace (nullable)
--   context     — JSON-encoded context map or raw string (nullable)
--   url         — Request URL (worker) or document URL (frontend), nullable
--   user_agent  — User-Agent header / navigator.userAgent, nullable
--   session_id  — Auth session ID if available, nullable
--   created_at  — ISO-8601 timestamp (D1 default)

-- ============================================================================
-- 1. Create error_events table
-- ============================================================================

CREATE TABLE IF NOT EXISTS "error_events" (
    "id"          TEXT NOT NULL,
    "source"      TEXT NOT NULL DEFAULT 'worker',
    "severity"    TEXT,
    "message"     TEXT NOT NULL,
    "stack"       TEXT,
    "context"     TEXT,
    "url"         TEXT,
    "user_agent"  TEXT,
    "session_id"  TEXT,
    "created_at"  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),

    PRIMARY KEY ("id"),

    -- Allowed source values
    CHECK ("source" IN ('worker', 'frontend')),

    -- Allowed severity values (nullable — not all events carry severity)
    CHECK ("severity" IN ('info', 'warning', 'error', 'fatal') OR "severity" IS NULL)
);

-- ============================================================================
-- 2. Indexes
-- ============================================================================

CREATE INDEX IF NOT EXISTS "idx_error_events_created_at"
    ON "error_events"("created_at");

CREATE INDEX IF NOT EXISTS "idx_error_events_source"
    ON "error_events"("source");

CREATE INDEX IF NOT EXISTS "idx_error_events_severity"
    ON "error_events"("severity");
