/**
 * Unified Authentication Middleware
 *
 * Authenticates requests via a four-tier chain:
 *   1. **API key** — Bearer token with `abc_` prefix, hashed & looked up in PostgreSQL
 *   2. **Better Auth (primary)** — Cookie or bearer-plugin session via the primary `authProvider`
 *   3. **Clerk JWT (deprecated fallback)** — Only attempted when a `fallbackProvider` is supplied
 *      and the primary provider found no session (no error). Set `DISABLE_CLERK_FALLBACK=true`
 *      to skip this step entirely.
 *   4. **Anonymous** — No credentials; falls through to anonymous context
 *
 * Token disambiguation:
 *   - API keys always start with `abc_` (generated by api-key-utils.ts)
 *   - Clerk JWTs are dot-separated base64 strings (header.payload.signature)
 *   - If a Bearer token matches neither pattern, it is rejected
 *
 * Legacy support:
 *   - `authenticateApiKey()` is preserved for backward compatibility but
 *     should be migrated to `authenticateRequestUnified()`.
 *
 * @see worker/middleware/clerk-jwt.ts — JWT verification
 * @see worker/types.ts — IAuthContext, IAuthMiddlewareResult, UserTier
 */

import type { Env, HyperdriveBinding, IAuthProvider } from '../types.ts';
import { ANONYMOUS_AUTH_CONTEXT, AuthScope, type IAuthContext, type IAuthMiddlewareResult, isTierSufficient, TIER_REGISTRY, UserTier } from '../types.ts';
import { ClerkAuthProvider } from './clerk-auth-provider.ts';
import { runTokenValidators } from './token-validator.ts';
import { ApiKeyRowSchema, UserTierRowSchema } from '../schemas.ts';
import { z } from 'zod';

// ============================================================================
// Types
// ============================================================================

/**
 * Result of API key authentication.
 */
export interface ApiKeyAuthResult {
    authenticated: boolean;
    userId?: string;
    apiKeyId?: string;
    scopes?: string[];
    error?: string;
}

/**
 * Authenticated request context attached after successful auth.
 */
export interface AuthContext {
    userId: string;
    apiKeyId: string;
    scopes: string[];
}

/**
 * Minimal pg Pool interface for auth queries.
 */
interface PgPool {
    query<T = Record<string, unknown>>(text: string, values?: unknown[]): Promise<{ rows: T[]; rowCount: number | null }>;
}

/**
 * Factory to create a pg Pool from a connection string.
 */
export type PgPoolFactory = (connectionString: string) => PgPool;

// ============================================================================
// Token Hashing
// ============================================================================

/**
 * Hashes an API key token using SHA-256.
 * Uses the Web Crypto API available in Cloudflare Workers.
 */
async function hashToken(token: string): Promise<string> {
    const encoder = new TextEncoder();
    const data = encoder.encode(token);
    const hashBuffer = await crypto.subtle.digest('SHA-256', data);
    const hashArray = Array.from(new Uint8Array(hashBuffer));
    return hashArray.map((b) => b.toString(16).padStart(2, '0')).join('');
}

/**
 * Extracts Bearer token from the Authorization header.
 * Returns null if no valid Bearer token is present.
 */
function extractBearerToken(request: Request): string | null {
    const authHeader = request.headers.get('Authorization');
    if (!authHeader) return null;

    const parts = authHeader.split(' ');
    if (parts.length !== 2 || parts[0].toLowerCase() !== 'bearer') return null;

    const token = parts[1].trim();
    return token.length > 0 ? token : null;
}

// ============================================================================
// Authentication
// ============================================================================

/**
 * Authenticates a request using an API key stored in PostgreSQL.
 *
 * @param request - Incoming HTTP request
 * @param hyperdrive - Cloudflare Hyperdrive binding
 * @param createPool - Factory to create a pg Pool
 * @param requiredScope - Scope the API key must have (e.g., 'compile', 'admin')
 * @returns Authentication result with user context
 *
 * @example
 * ```typescript
 * const auth = await authenticateApiKey(request, env.HYPERDRIVE, poolFactory, 'compile');
 * if (!auth.authenticated) {
 *     return JsonResponse.error(auth.error, 401);
 * }
 * // auth.userId, auth.apiKeyId, auth.scopes are available
 * ```
 */
export async function authenticateApiKey(
    request: Request,
    hyperdrive: HyperdriveBinding,
    createPool: PgPoolFactory,
    requiredScope?: AuthScope,
): Promise<ApiKeyAuthResult> {
    const token = extractBearerToken(request);
    if (!token) {
        return { authenticated: false, error: 'Missing or invalid Authorization header. Use: Bearer <api-key>' };
    }

    const keyHash = await hashToken(token);
    const pool = createPool(hyperdrive.connectionString);

    try {
        const result = await pool.query<{
            id: string;
            user_id: string;
            scopes: string[];
            rate_limit_per_minute: number;
            expires_at: string | null;
            revoked_at: string | null;
        }>(
            `SELECT id, user_id, scopes, rate_limit_per_minute, expires_at, revoked_at
             FROM api_keys
             WHERE key_hash = $1`,
            [keyHash],
        );

        if (result.rows.length === 0) {
            return { authenticated: false, error: 'Invalid API key' };
        }

        const rowParse = ApiKeyRowSchema.safeParse(result.rows[0]);
        if (!rowParse.success) {
            console.warn('[auth] Malformed API key DB row:', rowParse.error.issues);
            return { authenticated: false, error: 'Malformed API key data' };
        }
        const apiKey = rowParse.data;

        // Check if revoked
        if (apiKey.revoked_at) {
            return { authenticated: false, error: 'API key has been revoked' };
        }

        // Check if expired
        if (apiKey.expires_at && new Date(apiKey.expires_at) < new Date()) {
            return { authenticated: false, error: 'API key has expired' };
        }

        // Check scope
        if (requiredScope && !apiKey.scopes.includes(requiredScope)) {
            return {
                authenticated: false,
                error: `API key missing required scope: ${requiredScope}`,
            };
        }

        // Update last_used_at (fire-and-forget, don't block the response)
        pool.query(
            `UPDATE api_keys SET last_used_at = NOW() WHERE id = $1`,
            [apiKey.id],
        ).catch(() => {/* intentional: non-critical update */});

        return {
            authenticated: true,
            userId: apiKey.user_id,
            apiKeyId: apiKey.id,
            scopes: apiKey.scopes,
        };
    } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        return { authenticated: false, error: `Authentication service error: ${message}` };
    }
}

// ---------------------------------------------------------------------------
// Unified Authentication (Clerk JWT → API Key → Anonymous)
// ---------------------------------------------------------------------------

/** Check whether a Bearer token looks like an API key (abc_ prefix). */
function isApiKeyToken(token: string): boolean {
    return token.startsWith('abc_');
}

/** Check whether a Bearer token looks like a JWT (three dot-separated segments). */
function isJwtToken(token: string): boolean {
    const parts = token.split('.');
    return parts.length === 3 && parts.every((p) => p.length > 0);
}

/**
 * Authenticate a request using the unified four-tier chain.
 *
 * The chain tries, **in order**:
 *
 * 1. **API key (fast path, always checked first)** — If the Bearer token
 *    starts with `abc_` it is hashed and looked up in PostgreSQL via
 *    Hyperdrive. The authenticated user inherits their actual tier from the
 *    `users` table (not hardcoded).
 *
 * 2. **Primary auth provider (Better Auth)** — The `authProvider` param is
 *    always supplied by the caller (`BetterAuthProvider`). It is consulted
 *    for *every* non-API-key request, including requests with no Bearer
 *    token at all (to support cookie-based sessions). The provider receives
 *    the full request object and can inspect both `Authorization` headers
 *    and `Cookie` headers.
 *
 * 3. **Fallback auth provider (Clerk — deprecated)** — If the primary
 *    provider returned `{ valid: false }` **without** an error (= "no
 *    credentials present"), and a `fallbackProvider` is supplied, the
 *    fallback is attempted. This covers the Clerk→Better Auth migration
 *    period where some clients still send Clerk JWTs. Disabled when
 *    `DISABLE_CLERK_FALLBACK=true`.
 *
 * 4. **Anonymous** — When no provider authenticates the request it proceeds
 *    as {@link ANONYMOUS_AUTH_CONTEXT} (10 req/min rate limit, basic
 *    features).
 *
 * The function **never throws**. Auth failures are signalled via the optional
 * `response` field on the result — callers should check for a `response` and
 * short-circuit the request when present.
 *
 * @param request          - Incoming HTTP request
 * @param env              - Worker env bindings
 * @param createPool       - Optional pg Pool factory for API key lookups
 * @param authProvider     - Primary pluggable auth provider (Better Auth)
 * @param fallbackProvider - Optional deprecated fallback provider (Clerk)
 * @returns A {@link IAuthMiddlewareResult} with the resolved auth context
 */
export async function authenticateRequestUnified(
    request: Request,
    env: Env,
    createPool?: PgPoolFactory,
    authProvider?: IAuthProvider,
    fallbackProvider?: IAuthProvider,
): Promise<IAuthMiddlewareResult> {
    const token = extractBearerToken(request);

    // --- API key path (always checked first regardless of provider) ---
    if (token && isApiKeyToken(token)) {
        if (!env.HYPERDRIVE || !createPool) {
            return {
                context: { ...ANONYMOUS_AUTH_CONTEXT },
                response: new Response(
                    JSON.stringify({ error: 'API key authentication is not configured' }),
                    { status: 503, headers: { 'Content-Type': 'application/json' } },
                ),
            };
        }

        const result = await authenticateApiKey(request, env.HYPERDRIVE, createPool);
        if (result.authenticated) {
            // Resolve the key owner's actual tier from the database
            const ownerTier = await resolveApiKeyOwnerTier(
                result.userId,
                env.HYPERDRIVE,
                createPool,
            );

            const context: IAuthContext = {
                userId: result.userId ?? null,
                clerkUserId: null,
                tier: ownerTier,
                role: 'user',
                apiKeyId: result.apiKeyId ?? null,
                sessionId: null,
                scopes: result.scopes ?? [],
                authMethod: 'api-key',
            };
            return { context };
        }

        return {
            context: { ...ANONYMOUS_AUTH_CONTEXT },
            response: new Response(
                JSON.stringify({ error: result.error ?? 'Invalid API key' }),
                { status: 401, headers: { 'Content-Type': 'application/json' } },
            ),
        };
    }

    // --- Custom auth provider path (Better Auth and others) ---
    // When an explicit authProvider is supplied, delegate all non-API-key requests to it.
    // This covers:
    //   - No Bearer token: provider can check session cookies (e.g., Better Auth cookies)
    //   - Non-JWT Bearer token: provider handles session-ID tokens from the bearer plugin
    //   - JWT Bearer token: provider handles standard JWT verification
    // The provider receives the full request so it can inspect Authorization and Cookie headers.
    if (authProvider) {
        const providerResult = await authProvider.verifyToken(request);

        if (providerResult.valid && providerResult.providerUserId) {
            // Attempt to resolve the internal DB userId from the provider's user ID
            // when that ID is known to be a Clerk user id.
            //
            // When is `resolvedUserId` null vs. populated?
            //   - Better Auth: `providerUserId` is the user's D1 row id. The PostgreSQL
            //     users table (accessed via HYPERDRIVE) has no row for it, so we skip
            //     the Hyperdrive lookup entirely. This is EXPECTED — `clerkUserId`
            //     carries the BA user id, and downstream handlers use that field for
            //     Better Auth user lookups.
            //   - Clerk-backed custom providers: `providerUserId` is the Clerk user id.
            //     The PostgreSQL users table has a matching `clerk_user_id` row, so
            //     `resolvedUserId` is populated with the internal `users.id`.
            //   - No HYPERDRIVE / no createPool: resolution is skipped; `resolvedUserId`
            //     stays null for all providers (acceptable — handlers that need it must
            //     check and handle null themselves).
            let resolvedUserId: string | null = null;
            if (env.HYPERDRIVE && createPool && authProvider.authMethod !== 'better-auth') {
                try {
                    resolvedUserId = await resolveUserIdByClerkId(
                        providerResult.providerUserId,
                        env.HYPERDRIVE,
                        createPool,
                    );
                } catch (error) {
                    // Log detailed error server-side without leaking internals to the client
                    // deno-lint-ignore no-console
                    console.error('Authentication user lookup failed during resolveUserIdByClerkId:', error);
                    return {
                        context: { ...ANONYMOUS_AUTH_CONTEXT },
                        response: new Response(
                            JSON.stringify({ error: 'Authentication user lookup failed' }),
                            { status: 503, headers: { 'Content-Type': 'application/json' } },
                        ),
                    };
                }
            }

            const context: IAuthContext = {
                userId: resolvedUserId,
                clerkUserId: providerResult.providerUserId,
                tier: providerResult.tier ?? UserTier.Free,
                role: providerResult.role ?? 'user',
                apiKeyId: null,
                sessionId: providerResult.sessionId ?? null,
                scopes: [],
                authMethod: authProvider.authMethod,
            };

            // ZTA: run all registered token validators (tamper detection, revocation, etc.)
            // Pass the token (or empty string for cookie-based auth) to the validators.
            const validationResult = await runTokenValidators(token ?? '', context, env);
            if (!validationResult.valid) {
                return {
                    context: { ...ANONYMOUS_AUTH_CONTEXT },
                    response: new Response(
                        JSON.stringify({ success: false, error: validationResult.error ?? 'Token validation failed' }),
                        { status: 401, headers: { 'Content-Type': 'application/json' } },
                    ),
                };
            }

            return { context };
        }

        // Primary provider found no valid session.
        // If the provider returned an explicit error (rejected the token), return 401
        // immediately — do NOT fall through to the fallback.
        if (token && providerResult.error) {
            return {
                context: { ...ANONYMOUS_AUTH_CONTEXT },
                response: new Response(
                    JSON.stringify({ success: false, error: 'Authentication failed' }),
                    { status: 401, headers: { 'Content-Type': 'application/json' } },
                ),
            };
        }

        // ── Clerk fallback (deprecated) ──────────────────────────────────────
        // The primary provider returned { valid: false } WITHOUT an error, meaning
        // "no credentials I recognise were present". If a fallbackProvider (Clerk)
        // is configured and the Bearer token looks like a JWT, try it.
        if (fallbackProvider && token && isJwtToken(token)) {
            const fbResult = await fallbackProvider.verifyToken(request);

            if (fbResult.valid && fbResult.providerUserId) {
                // deno-lint-ignore no-console
                console.warn(
                    '[auth] Request authenticated via DEPRECATED Clerk fallback. ' +
                    'Migrate this client to Better Auth. Set DISABLE_CLERK_FALLBACK=true to remove this path.',
                );

                let resolvedUserId: string | null = null;
                if (env.HYPERDRIVE && createPool) {
                    try {
                        resolvedUserId = await resolveUserIdByClerkId(
                            fbResult.providerUserId,
                            env.HYPERDRIVE,
                            createPool,
                        );
                    } catch (error) {
                        const message = error instanceof Error ? error.message : String(error);
                        return {
                            context: { ...ANONYMOUS_AUTH_CONTEXT },
                            response: new Response(
                                JSON.stringify({ error: `Authentication user lookup failed: ${message}` }),
                                { status: 503, headers: { 'Content-Type': 'application/json' } },
                            ),
                        };
                    }
                }

                const fbContext: IAuthContext = {
                    userId: resolvedUserId,
                    clerkUserId: fbResult.providerUserId,
                    tier: fbResult.tier ?? UserTier.Free,
                    role: fbResult.role ?? 'user',
                    apiKeyId: null,
                    sessionId: fbResult.sessionId ?? null,
                    scopes: [],
                    authMethod: fallbackProvider.authMethod,
                };

                // ZTA: run validators on the fallback token too
                const fbValidation = await runTokenValidators(token, fbContext, env);
                if (!fbValidation.valid) {
                    return {
                        context: { ...ANONYMOUS_AUTH_CONTEXT },
                        response: new Response(
                            JSON.stringify({ success: false, error: fbValidation.error ?? 'Token validation failed' }),
                            { status: 401, headers: { 'Content-Type': 'application/json' } },
                        ),
                    };
                }

                return { context: fbContext };
            }

            // Fallback also failed — if it returned an error, surface it as 401
            if (fbResult.error) {
                return {
                    context: { ...ANONYMOUS_AUTH_CONTEXT },
                    response: new Response(
                        JSON.stringify({ success: false, error: fbResult.error ?? 'Invalid JWT' }),
                        { status: 401, headers: { 'Content-Type': 'application/json' } },
                    ),
                };
            }
        }

        // No provider authenticated — anonymous
        return { context: { ...ANONYMOUS_AUTH_CONTEXT } };
    }

    // --- No authProvider supplied at all (shouldn't happen after P3 inversion, but kept for safety) ---

    // --- No token → anonymous ---
    if (!token) {
        return { context: { ...ANONYMOUS_AUTH_CONTEXT } };
    }

    // --- JWT path (legacy Clerk-only mode, no custom authProvider supplied) ---
    if (isJwtToken(token)) {
        const provider = new ClerkAuthProvider(env);
        const providerResult = await provider.verifyToken(request);

        if (providerResult.valid && providerResult.providerUserId) {
            let resolvedUserId: string | null = null;
            if (env.HYPERDRIVE && createPool) {
                try {
                    resolvedUserId = await resolveUserIdByClerkId(
                        providerResult.providerUserId,
                        env.HYPERDRIVE,
                        createPool,
                    );
                } catch (error) {
                    const message = error instanceof Error ? error.message : String(error);
                    return {
                        context: { ...ANONYMOUS_AUTH_CONTEXT },
                        response: new Response(
                            JSON.stringify({ error: `Authentication user lookup failed: ${message}` }),
                            { status: 503, headers: { 'Content-Type': 'application/json' } },
                        ),
                    };
                }
            }

            const context: IAuthContext = {
                userId: resolvedUserId,
                clerkUserId: providerResult.providerUserId,
                tier: providerResult.tier ?? UserTier.Free,
                role: providerResult.role ?? 'user',
                apiKeyId: null,
                sessionId: providerResult.sessionId ?? null,
                scopes: [],
                authMethod: provider.authMethod,
            };

            // ZTA: run all registered token validators (tamper detection, revocation, etc.)
            const validationResult = await runTokenValidators(token, context, env);
            if (!validationResult.valid) {
                return {
                    context: { ...ANONYMOUS_AUTH_CONTEXT },
                    response: new Response(
                        JSON.stringify({ success: false, error: validationResult.error ?? 'Token validation failed' }),
                        { status: 401, headers: { 'Content-Type': 'application/json' } },
                    ),
                };
            }

            return { context };
        }

        return {
            context: { ...ANONYMOUS_AUTH_CONTEXT },
            response: new Response(
                JSON.stringify({ success: false, error: providerResult.error ?? 'Invalid JWT' }),
                { status: 401, headers: { 'Content-Type': 'application/json' } },
            ),
        };
    }

    // --- Unrecognised token format ---
    return {
        context: { ...ANONYMOUS_AUTH_CONTEXT },
        response: new Response(
            JSON.stringify({ success: false, error: 'Unrecognised credential format — expected a JWT or abc_-prefixed API key' }),
            { status: 401, headers: { 'Content-Type': 'application/json' } },
        ),
    };
}

// ---------------------------------------------------------------------------
// Clerk User Resolution
// ---------------------------------------------------------------------------

/**
 * Resolve internal `users.id` from Clerk `clerk_user_id`.
 */
async function resolveUserIdByClerkId(
    clerkUserId: string,
    hyperdrive: HyperdriveBinding,
    createPool: PgPoolFactory,
): Promise<string | null> {
    const pool = createPool(hyperdrive.connectionString);
    const result = await pool.query(
        `SELECT id FROM users WHERE clerk_user_id = $1 LIMIT 1`,
        [clerkUserId],
    );

    const rowParse = z.object({ id: z.string().min(1) }).safeParse(result.rows[0]);
    return rowParse.success ? rowParse.data.id : null;
}

// ---------------------------------------------------------------------------
// API Key Tier Resolution
// ---------------------------------------------------------------------------

/**
 * Look up the actual tier of an API key's owner from the `users` table.
 * Falls back to {@link UserTier.Free} if the user cannot be found or on error.
 */
async function resolveApiKeyOwnerTier(
    userId: string | undefined,
    hyperdrive: HyperdriveBinding,
    createPool: PgPoolFactory,
): Promise<UserTier> {
    if (!userId) return UserTier.Free;

    try {
        const pool = createPool(hyperdrive.connectionString);
        const result = await pool.query(
            `SELECT tier FROM users WHERE id = $1 LIMIT 1`,
            [userId],
        );

        if (result.rows.length > 0) {
            const rowParse = UserTierRowSchema.safeParse(result.rows[0]);
            if (rowParse.success) {
                return rowParse.data.tier;
            }
            // Unknown/invalid tier value — fall back to Free
            console.warn('[auth] Unrecognised tier value in DB row, defaulting to Free');
        }
        return UserTier.Free;
    } catch {
        // Non-critical: fall back to Free tier on DB errors
        return UserTier.Free;
    }
}

// ============================================================================
// Auth Guard Helpers
// ============================================================================

/**
 * Returns a 401 JSON response if the auth context is anonymous, or `null` if
 * the user is authenticated. Use as an early-return guard:
 *
 * ```ts
 * const denied = requireAuth(authContext);
 * if (denied) return denied;
 * ```
 */
export function requireAuth(context: IAuthContext): Response | null {
    if (context.authMethod === 'anonymous') {
        return new Response(
            JSON.stringify({ success: false, error: 'Authentication required' }),
            { status: 401, headers: { 'Content-Type': 'application/json' } },
        );
    }
    return null;
}

/**
 * Returns a 403 JSON response if the user's tier is below the required minimum,
 * or `null` if the tier is sufficient. Tier ordering is derived from
 * {@link TIER_REGISTRY} — adding a new tier only requires updating the registry.
 *
 * ```ts
 * const denied = requireTier(authContext, UserTier.Pro);
 * if (denied) return denied;
 * ```
 */
export function requireTier(context: IAuthContext, minTier: UserTier): Response | null {
    if (!isTierSufficient(context.tier, minTier)) {
        return new Response(
            JSON.stringify({
                success: false,
                error: `Insufficient tier: requires ${TIER_REGISTRY[minTier].displayName}, current tier is ${TIER_REGISTRY[context.tier].displayName}`,
            }),
            { status: 403, headers: { 'Content-Type': 'application/json' } },
        );
    }
    return null;
}

/**
 * Returns a 403 JSON response if the auth context is missing any of the
 * required scopes, or `null` if scope requirements are met.
 *
 * **JWT-authenticated users** (authMethod === 'clerk-jwt') are treated as
 * having all scopes — they are the resource owner and can do anything their
 * tier allows. Only **API-key authenticated** requests are scope-restricted.
 *
 * ```ts
 * const denied = requireScope(authContext, 'compile');
 * if (denied) return denied;
 * ```
 */
export function requireScope(context: IAuthContext, ...requiredScopes: string[]): Response | null {
    // JWT/session-authenticated users (Clerk or Better Auth) bypass scope
    // checks — they own the account and are limited only by tier, not by
    // API-key scopes.
    if (context.authMethod === 'clerk-jwt' || context.authMethod === 'better-auth') {
        return null;
    }

    // Anonymous users cannot have scopes — they should be caught by requireAuth
    // first, but guard defensively.
    if (context.authMethod === 'anonymous') {
        return new Response(
            JSON.stringify({ success: false, error: 'Authentication required' }),
            { status: 401, headers: { 'Content-Type': 'application/json' } },
        );
    }

    // API-key users: check that every required scope is present
    const missing = requiredScopes.filter((s) => !context.scopes.includes(s));
    if (missing.length > 0) {
        return new Response(
            JSON.stringify({
                success: false,
                error: `Missing required scope${missing.length > 1 ? 's' : ''}: ${missing.join(', ')}`,
            }),
            { status: 403, headers: { 'Content-Type': 'application/json' } },
        );
    }
    return null;
}
