/**
 * Unified Authentication Middleware
 *
 * Authenticates requests via a three-tier chain:
 *   1. **API key** — Bearer token with `abc_` prefix, hashed & looked up in PostgreSQL
 *   2. **Better Auth** — Cookie or bearer-plugin session via the primary `authProvider`
 *   3. **Anonymous** — No credentials; falls through to anonymous context
 *
 * Token disambiguation:
 *   - API keys always start with `abc_` (generated by api-key-utils.ts)
 *   - If a Bearer token does not match the API key pattern, it is handled by
 *     the auth provider (Better Auth bearer plugin tokens, etc.)
 *   - If a Bearer token matches neither pattern, it is rejected
 *
 * Legacy support:
 *   - `authenticateApiKey()` is preserved for backward compatibility but
 *     should be migrated to `authenticateRequestUnified()`.
 *
 * @see worker/types.ts — IAuthContext, IAuthMiddlewareResult, UserTier
 */

import type { Env, HyperdriveBinding, IAuthProvider } from '../types.ts';
import { ANONYMOUS_AUTH_CONTEXT, type IAuthContext, type IAuthMiddlewareResult, isTierSufficient, TIER_REGISTRY, UserTier } from '../types.ts';
import { runTokenValidators } from './token-validator.ts';
import { UserTierRowSchema } from '../schemas.ts';
import { createPrismaClient } from '../lib/prisma.ts';
import { AnalyticsService } from '../../src/services/AnalyticsService.ts';

// ============================================================================
// Types
// ============================================================================

/**
 * Result of API key authentication.
 */
export interface ApiKeyAuthResult {
    authenticated: boolean;
    userId?: string;
    apiKeyId?: string;
    scopes?: string[];
    rateLimitPerMinute?: number | null;
    error?: string;
}

/**
 * Authenticated request context attached after successful auth.
 */
export interface AuthContext {
    userId: string;
    apiKeyId: string;
    scopes: string[];
}

// ============================================================================
// Token Hashing
// ============================================================================

/**
 * Hashes an API key token using SHA-256.
 * Uses the Web Crypto API available in Cloudflare Workers.
 */
async function hashToken(token: string): Promise<string> {
    const encoder = new TextEncoder();
    const data = encoder.encode(token);
    const hashBuffer = await crypto.subtle.digest('SHA-256', data);
    const hashArray = Array.from(new Uint8Array(hashBuffer));
    return hashArray.map((b) => b.toString(16).padStart(2, '0')).join('');
}

/**
 * Extracts Bearer token from the Authorization header.
 * Returns null if no valid Bearer token is present.
 */
function extractBearerToken(request: Request): string | null {
    const authHeader = request.headers.get('Authorization');
    if (!authHeader) return null;

    const parts = authHeader.split(' ');
    if (parts.length !== 2 || parts[0].toLowerCase() !== 'bearer') return null;

    const token = parts[1].trim();
    return token.length > 0 ? token : null;
}

// ============================================================================
// Authentication
// ============================================================================

/**
 * Authenticates a request using an API key stored in PostgreSQL via Prisma.
 *
 * @param request - Incoming HTTP request
 * @param hyperdrive - Cloudflare Hyperdrive binding
 * @returns Authentication result with user context
 */
export async function authenticateApiKey(
    request: Request,
    hyperdrive: HyperdriveBinding,
): Promise<ApiKeyAuthResult> {
    const token = extractBearerToken(request);
    if (!token) {
        return { authenticated: false, error: 'Missing or invalid Authorization header. Use: Bearer <api-key>' };
    }

    const keyHash = await hashToken(token);

    // Cloudflare Workers are isolated per-request — there is no shared singleton
    // state between invocations.  Creating a PrismaClient here is the standard
    // Workers pattern; connection pooling is handled at the infrastructure level
    // by Hyperdrive, not by the client instance.
    const prisma = createPrismaClient(hyperdrive.connectionString);

    try {
        const apiKey = await prisma.apiKey.findFirst({
            where: { keyHash },
            select: { id: true, userId: true, scopes: true, rateLimitPerMinute: true, expiresAt: true, revokedAt: true },
        });

        if (!apiKey) {
            return { authenticated: false, error: 'Invalid API key' };
        }

        // Check if revoked
        if (apiKey.revokedAt) {
            return { authenticated: false, error: 'API key has been revoked' };
        }

        // Check if expired
        if (apiKey.expiresAt && apiKey.expiresAt < new Date()) {
            return { authenticated: false, error: 'API key has expired' };
        }

        // Update lastUsedAt as a non-blocking side-effect.  `lastUsedAt` is
        // purely informational analytics data.  Loss on short-lived requests
        // is expected and acceptable — a failure here must never abort the
        // authentication result.  Hyperdrive typically completes the write
        // before the Worker terminates, but this is not guaranteed.
        prisma.apiKey.update({ where: { id: apiKey.id }, data: { lastUsedAt: new Date() } }).catch(() => {});

        return {
            authenticated: true,
            userId: apiKey.userId,
            apiKeyId: apiKey.id,
            scopes: apiKey.scopes,
            rateLimitPerMinute: apiKey.rateLimitPerMinute ?? null,
        };
    } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        return { authenticated: false, error: `Authentication service error: ${message}` };
    }
}

// ---------------------------------------------------------------------------
// Unified Authentication (API Key → Better Auth → Anonymous)
// ---------------------------------------------------------------------------

/** Check whether a Bearer token looks like an API key (abc_ prefix). */
function isApiKeyToken(token: string): boolean {
    return token.startsWith('abc_');
}

/**
 * Authenticate a request using the unified three-tier chain.
 *
 * The chain tries, **in order**:
 *
 * 1. **API key (fast path, always checked first)** — If the Bearer token
 *    starts with `abc_` it is hashed and looked up in PostgreSQL via
 *    Hyperdrive using Prisma. The authenticated user inherits their actual
 *    tier from the `users` table (not hardcoded).
 *
 * 2. **Primary auth provider (Better Auth)** — The `authProvider` param is
 *    always supplied by the caller (`BetterAuthProvider`). It is consulted
 *    for *every* non-API-key request, including requests with no Bearer
 *    token at all (to support cookie-based sessions). The provider receives
 *    the full request object and can inspect both `Authorization` headers
 *    and `Cookie` headers.
 *
 * 3. **Anonymous** — When no provider authenticates the request it proceeds
 *    as {@link ANONYMOUS_AUTH_CONTEXT} (10 req/min rate limit, basic
 *    features).
 *
 * The function **never throws**. Auth failures are signalled via the optional
 * `response` field on the result — callers should check for a `response` and
 * short-circuit the request when present.
 *
 * @param request          - Incoming HTTP request
 * @param env              - Worker env bindings
 * @param authProvider     - Primary pluggable auth provider (Better Auth)
 * @returns A {@link IAuthMiddlewareResult} with the resolved auth context
 */
export async function authenticateRequestUnified(
    request: Request,
    env: Env,
    authProvider?: IAuthProvider,
): Promise<IAuthMiddlewareResult> {
    const token = extractBearerToken(request);

    // --- API key path (always checked first regardless of provider) ---
    if (token && isApiKeyToken(token)) {
        if (!env.HYPERDRIVE) {
            return {
                context: { ...ANONYMOUS_AUTH_CONTEXT },
                response: new Response(
                    JSON.stringify({ error: 'API key authentication is not configured' }),
                    { status: 503, headers: { 'Content-Type': 'application/json' } },
                ),
            };
        }

        const result = await authenticateApiKey(request, env.HYPERDRIVE);
        if (result.authenticated) {
            // Resolve the key owner's actual tier from the database
            const ownerTier = await resolveApiKeyOwnerTier(
                result.userId,
                env.HYPERDRIVE,
            );

            const context: IAuthContext = {
                userId: result.userId ?? null,
                tier: ownerTier,
                role: 'user',
                apiKeyId: result.apiKeyId ?? null,
                sessionId: null,
                scopes: result.scopes ?? [],
                authMethod: 'api-key',
                apiKeyRateLimit: result.rateLimitPerMinute ?? null,
            };

            // ZTA telemetry: track successful API key authentication
            if (env.ANALYTICS_ENGINE) {
                new AnalyticsService(env.ANALYTICS_ENGINE).trackSecurityEvent({
                    eventType: 'auth_success',
                    authMethod: 'api-key',
                    userId: result.userId,
                });
            }

            return { context };
        }

        // ZTA telemetry: track failed API key authentication
        if (env.ANALYTICS_ENGINE) {
            new AnalyticsService(env.ANALYTICS_ENGINE).trackSecurityEvent({
                eventType: 'auth_failure',
                authMethod: 'api-key',
                reason: result.error ?? 'Invalid API key',
            });
        }

        return {
            context: { ...ANONYMOUS_AUTH_CONTEXT },
            response: new Response(
                JSON.stringify({ error: result.error ?? 'Invalid API key' }),
                { status: 401, headers: { 'Content-Type': 'application/json' } },
            ),
        };
    }

    // --- Custom auth provider path (Better Auth and others) ---
    // When an explicit authProvider is supplied, delegate all non-API-key requests to it.
    // This covers:
    //   - No Bearer token: provider can check session cookies (e.g., Better Auth cookies)
    //   - Non-JWT Bearer token: provider handles session-ID tokens from the bearer plugin
    //   - JWT Bearer token: provider handles standard JWT verification
    // The provider receives the full request so it can inspect Authorization and Cookie headers.
    if (authProvider) {
        const providerResult = await authProvider.verifyToken(request);

        if (providerResult.valid && providerResult.providerUserId) {
            const context: IAuthContext = {
                userId: providerResult.providerUserId,
                tier: providerResult.tier ?? UserTier.Free,
                role: providerResult.role ?? 'user',
                apiKeyId: null,
                sessionId: providerResult.sessionId ?? null,
                scopes: [],
                authMethod: authProvider.authMethod,
                email: providerResult.email ?? null,
                displayName: providerResult.displayName ?? null,
                apiKeyRateLimit: null,
            };

            // ZTA: run all registered token validators (tamper detection, revocation, etc.)
            // Pass the token (or empty string for cookie-based auth) to the validators.
            const validationResult = await runTokenValidators(token ?? '', context, env);
            if (!validationResult.valid) {
                return {
                    context: { ...ANONYMOUS_AUTH_CONTEXT },
                    response: new Response(
                        JSON.stringify({ success: false, error: validationResult.error ?? 'Token validation failed' }),
                        { status: 401, headers: { 'Content-Type': 'application/json' } },
                    ),
                };
            }

            // ZTA telemetry: track successful session auth
            if (env.ANALYTICS_ENGINE) {
                new AnalyticsService(env.ANALYTICS_ENGINE).trackSecurityEvent({
                    eventType: 'auth_success',
                    authMethod: authProvider.authMethod,
                    userId: providerResult.providerUserId ?? undefined,
                });
            }

            return { context };
        }

        // Primary provider found no valid session.
        // If the provider returned an explicit error (rejected the token), return 401.
        if (token && providerResult.error) {
            return {
                context: { ...ANONYMOUS_AUTH_CONTEXT },
                response: new Response(
                    JSON.stringify({ success: false, error: 'Authentication failed' }),
                    { status: 401, headers: { 'Content-Type': 'application/json' } },
                ),
            };
        }

        // No provider authenticated — anonymous
        return { context: { ...ANONYMOUS_AUTH_CONTEXT } };
    }

    // --- No authProvider supplied at all — anonymous fallback ---

    // --- No token → anonymous ---
    if (!token) {
        return { context: { ...ANONYMOUS_AUTH_CONTEXT } };
    }

    // --- Unrecognised token format ---
    return {
        context: { ...ANONYMOUS_AUTH_CONTEXT },
        response: new Response(
            JSON.stringify({ success: false, error: 'Unrecognised credential format — expected an abc_-prefixed API key' }),
            { status: 401, headers: { 'Content-Type': 'application/json' } },
        ),
    };
}

// ---------------------------------------------------------------------------
// API Key Tier Resolution
// ---------------------------------------------------------------------------

/**
 * Look up the actual tier of an API key's owner from the `users` table.
 * Falls back to {@link UserTier.Free} if the user cannot be found or on error.
 */
async function resolveApiKeyOwnerTier(
    userId: string | undefined,
    hyperdrive: HyperdriveBinding,
): Promise<UserTier> {
    if (!userId) return UserTier.Free;

    try {
        // See note in authenticateApiKey: PrismaClient creation per request is
        // correct for Cloudflare Workers; Hyperdrive pools connections externally.
        const prisma = createPrismaClient(hyperdrive.connectionString);
        const row = await prisma.user.findUnique({
            where: { id: userId },
            select: { tier: true },
        });

        if (row) {
            const rowParse = UserTierRowSchema.safeParse(row);
            if (rowParse.success) {
                return rowParse.data.tier;
            }
            // Unknown/invalid tier value — fall back to Free
            // deno-lint-ignore no-console
            console.warn('[auth] Unrecognised tier value in DB row, defaulting to Free');
        }
        return UserTier.Free;
    } catch {
        // Non-critical: fall back to Free tier on DB errors
        return UserTier.Free;
    }
}

// ============================================================================
// Auth Guard Helpers
// ============================================================================

/**
 * Returns a 401 JSON response if the auth context is anonymous, or `null` if
 * the user is authenticated. Use as an early-return guard:
 *
 * ```ts
 * const denied = requireAuth(authContext);
 * if (denied) return denied;
 * ```
 */
export function requireAuth(context: IAuthContext): Response | null {
    if (context.authMethod === 'anonymous') {
        return new Response(
            JSON.stringify({ success: false, error: 'Authentication required' }),
            { status: 401, headers: { 'Content-Type': 'application/json' } },
        );
    }
    return null;
}

/**
 * Returns a 403 JSON response if the user's tier is below the required minimum,
 * or `null` if the tier is sufficient. Tier ordering is derived from
 * {@link TIER_REGISTRY} — adding a new tier only requires updating the registry.
 *
 * ```ts
 * const denied = requireTier(authContext, UserTier.Pro);
 * if (denied) return denied;
 * ```
 */
export function requireTier(context: IAuthContext, minTier: UserTier): Response | null {
    if (!isTierSufficient(context.tier, minTier)) {
        return new Response(
            JSON.stringify({
                success: false,
                error: `Insufficient tier: requires ${TIER_REGISTRY[minTier].displayName}, current tier is ${TIER_REGISTRY[context.tier].displayName}`,
            }),
            { status: 403, headers: { 'Content-Type': 'application/json' } },
        );
    }
    return null;
}

/**
 * Returns a 403 JSON response if the auth context is missing any of the
 * required scopes, or `null` if scope requirements are met.
 *
 * **Session-authenticated users** (authMethod === 'better-auth') are treated as
 * having all scopes — they are the resource owner and can do anything their
 * tier allows. Only **API-key authenticated** requests are scope-restricted.
 *
 * ```ts
 * const denied = requireScope(authContext, 'compile');
 * if (denied) return denied;
 * ```
 */
export function requireScope(context: IAuthContext, ...requiredScopes: string[]): Response | null {
    // Session-authenticated users (Better Auth) bypass scope
    // checks — they own the account and are limited only by tier, not by
    // API-key scopes.
    if (context.authMethod === 'better-auth') {
        return null;
    }

    // Anonymous users cannot have scopes — they should be caught by requireAuth
    // first, but guard defensively.
    if (context.authMethod === 'anonymous') {
        return new Response(
            JSON.stringify({ success: false, error: 'Authentication required' }),
            { status: 401, headers: { 'Content-Type': 'application/json' } },
        );
    }

    // API-key users: check that every required scope is present
    const missing = requiredScopes.filter((s) => !context.scopes.includes(s));
    if (missing.length > 0) {
        return new Response(
            JSON.stringify({
                success: false,
                error: `Missing required scope${missing.length > 1 ? 's' : ''}: ${missing.join(', ')}`,
            }),
            { status: 403, headers: { 'Content-Type': 'application/json' } },
        );
    }
    return null;
}
