// ⚠️  This file is intentionally left here as a reference only.
//
// Prisma 7 discovers `prisma.config.ts` at the **project root**, not inside
// the `prisma/` subdirectory. The authoritative config has been moved to:
//
//   /prisma.config.ts  (project root)
//
// Do NOT edit this file — edit the root-level `prisma.config.ts` instead.
// This file is never loaded by the Prisma CLI.
