import { Component, signal } from '@angular/core';

@Component({
    selector: 'app-how-it-works-section',
    standalone: true,
    template: `
    <section class="bloqr-section" id="how-it-works" aria-label="How It Works">
        <div class="bloqr-container">
            <span class="bloqr-section-label">HOW IT WORKS</span>
            <h2 class="bloqr-section-title">Set it. Bloqr it. Forget it.</h2>
            <div class="steps-grid" role="list">
                @for (step of steps; track step.num) {
                    <div class="step" role="listitem">
                        <div class="step-num" aria-hidden="true">{{ step.num }}</div>
                        <div class="step-content">
                            <h3 class="step-title">{{ step.title }}</h3>
                            <p class="step-body">{{ step.body }}</p>
                        </div>
                    </div>
                }
            </div>
            <!-- Code/UI Toggle -->
            <div class="toggle-section">
                <p class="toggle-copy">You'll never write a line of this. The UI builds it for you. But it's here if you want it.</p>
                <div class="toggle-controls">
                    <button class="toggle-btn" [class.active]="!showCode()" (click)="showCode.set(false)">
                        Show UI
                    </button>
                    <button class="toggle-btn" [class.active]="showCode()" (click)="showCode.set(true)">
                        Show code
                    </button>
                </div>
                <div class="toggle-view">
                    @if (!showCode()) {
                        <div class="ui-mockup bloqr-card">
                            <div class="ui-form-row">
                                <p class="ui-label">DNS Vendor</p>
                                <div class="ui-select" role="presentation">AdGuard Home</div>
                            </div>
                            <div class="ui-form-row">
                                <p class="ui-label">List profile</p>
                                <div class="ui-select" role="presentation">Balanced (AI-recommended)</div>
                            </div>
                            <div class="ui-form-row">
                                <p class="ui-label">Update frequency</p>
                                <div class="ui-select" role="presentation">Every 6 hours</div>
                            </div>
                            <div class="ui-form-row">
                                <p class="ui-label">Devices</p>
                                <div class="ui-tags" role="presentation">
                                    <span class="ui-tag">Home network</span>
                                    <span class="ui-tag">Mobile</span>
                                    <span class="ui-tag">+ Add device</span>
                                </div>
                            </div>
                            <button class="bloqr-btn-primary" style="margin-top:16px; cursor:default;">Apply configuration</button>
                        </div>
                    } @else {
                        <div class="code-block" aria-label="Configuration YAML">
<pre><code><span class="code-comment"># Bloqr configuration — generated by the UI</span>
<span class="code-key">vendor</span>: adguard-home
<span class="code-key">profile</span>: balanced
<span class="code-key">update_frequency</span>: 6h
<span class="code-key">devices</span>:
  - <span class="code-string">home_network</span>
  - <span class="code-string">mobile</span>
<span class="code-key">ai</span>:
  <span class="code-key">enabled</span>: <span class="code-bool">true</span>
  <span class="code-key">threat_intel</span>: <span class="code-bool">true</span>
  <span class="code-key">auto_update</span>: <span class="code-bool">true</span></code></pre>
                        </div>
                    }
                </div>
            </div>
        </div>
    </section>
    `,
    styles: [`
    :host { display: block; }
    .steps-grid {
        display: grid;
        grid-template-columns: repeat(3, 1fr);
        gap: 32px;
        margin: 48px 0;
        position: relative;
    }
    .steps-grid::before {
        content: '';
        position: absolute;
        top: 24px;
        left: calc(16.666% + 16px);
        right: calc(16.666% + 16px);
        height: 1px;
        background: linear-gradient(90deg, #FF5500, #1E2D40, #FF5500);
        opacity: 0.3;
    }
    .step { display: flex; flex-direction: column; gap: 16px; align-items: flex-start; }
    .step-num {
        width: 48px; height: 48px;
        background: rgba(255,85,0,0.1);
        border: 1px solid rgba(255,85,0,0.3);
        border-radius: 50%;
        display: flex; align-items: center; justify-content: center;
        font-family: 'Space Grotesk', sans-serif;
        font-weight: 800;
        font-size: 1.1rem;
        color: #FF5500;
        flex-shrink: 0;
        position: relative;
        z-index: 1;
        background-color: #070B14;
    }
    .step-title {
        font-family: 'Space Grotesk', sans-serif;
        font-size: 1rem;
        font-weight: 700;
        color: #F1F5F9;
        margin: 0 0 8px;
    }
    .step-body { font-size: 0.875rem; color: #94A3B8; line-height: 1.6; margin: 0; }
    .toggle-section { margin-top: 48px; }
    .toggle-copy { font-size: 0.95rem; color: #94A3B8; margin-bottom: 20px; font-style: italic; }
    .toggle-controls {
        display: flex;
        gap: 0;
        margin-bottom: 24px;
        background: #0E1829;
        border: 1px solid #1E2D40;
        border-radius: 8px;
        padding: 4px;
        width: fit-content;
    }
    .toggle-btn {
        background: none;
        border: none;
        padding: 8px 20px;
        font-family: 'Space Grotesk', sans-serif;
        font-size: 13px;
        font-weight: 500;
        color: #94A3B8;
        cursor: pointer;
        border-radius: 6px;
        transition: background 0.2s, color 0.2s;
    }
    .toggle-btn.active { background: #1E2D40; color: #F1F5F9; }
    .toggle-view { max-width: 640px; }
    .code-block {
        background: #0E1829;
        border: 1px solid #1E2D40;
        border-radius: 8px;
        overflow: hidden;
    }
    .code-block pre {
        margin: 0;
        padding: 24px;
        font-family: 'JetBrains Mono', monospace;
        font-size: 13px;
        line-height: 1.6;
        color: #F1F5F9;
        background: none;
        border: none;
        border-radius: 0;
        overflow-x: auto;
    }
    .code-block code { background: none; border: none; padding: 0; font-family: inherit; }
    .code-comment { color: #475569; }
    .code-key { color: #00D4FF; }
    .code-string { color: #22C55E; }
    .code-bool { color: #FF5500; }
    .ui-mockup { display: flex; flex-direction: column; gap: 16px; }
    .ui-form-row { display: flex; flex-direction: column; gap: 6px; }
    .ui-label { font-size: 12px; font-weight: 600; color: #94A3B8; text-transform: uppercase; letter-spacing: 0.08em; }
    .ui-select {
        background: #162035; border: 1px solid #1E2D40; border-radius: 6px;
        padding: 10px 14px; font-size: 14px; color: #F1F5F9;
    }
    .ui-tags { display: flex; gap: 8px; flex-wrap: wrap; }
    .ui-tag {
        background: rgba(0,212,255,0.08); border: 1px solid rgba(0,212,255,0.2);
        color: #00D4FF; border-radius: 6px; padding: 6px 12px; font-size: 12px; font-weight: 500;
    }
    @media (max-width: 768px) {
        .steps-grid { grid-template-columns: 1fr; }
        .steps-grid::before { display: none; }
    }
    `],
})
export class HowItWorksSectionComponent {
    readonly showCode = signal(false);

    readonly steps = [
        { num: '01', title: 'Connect your vendor', body: 'Link your AdGuard, NextDNS, or Pi-hole account. Or let us pick one for you.' },
        { num: '02', title: 'We build your list', body: 'AI compiles, deduplicates, and maintains a filter list tailored to your setup.' },
        { num: '03', title: 'Stay protected', body: 'Every device. Every network. One change propagates everywhere, instantly.' },
    ];
}
