$kind: http-request
description: Returns the default compiler configuration schema.
url: {{baseUrl}}/configuration/defaults
method: GET
headers:
  Accept: application/json
  X-API-Key: "{{apiKey}}"
body:
  type: text
  content: ""
order: 1000
