/**
 * RFC 9457 Problem Details for HTTP APIs.
 *
 * Produces structured, machine-readable error responses using the
 * `application/problem+json` media type as defined in RFC 9457
 * (https://www.rfc-editor.org/rfc/rfc9457).
 *
 * ## Why RFC 9457?
 *
 * Standard JSON error envelopes (`{ success: false, error: "..." }`) are
 * sufficient for simple cases but provide no interoperability guarantee.
 * RFC 9457 defines a shared vocabulary — `type`, `title`, `status`, `detail`,
 * `instance` — that HTTP clients and agents (browsers, proxies, adblocker
 * detection logic) can rely on without out-of-band documentation.
 *
 * A response with `Content-Type: application/problem+json` signals to any
 * conforming client (including future browser agent error-page renderers) that
 * the body describes a problem and MUST be displayed, not silently swallowed.
 *
 * ## Problem type URIs
 *
 * Each factory method in {@link ProblemResponse} maps to a stable, versioned
 * URI under `https://adblock-compiler.jk-com.workers.dev/probs/`.
 * Callers can register these URIs in their own documentation to let agents
 * render appropriate guidance (e.g. "disable your adblocker to access the
 * Turnstile-protected endpoint").
 *
 * ## Usage
 *
 * ```typescript
 * // From a Hono route handler or middleware:
 * return ProblemResponse.rateLimited(c.req.path, 30);
 *
 * // Override the default detail message:
 * return ProblemResponse.forbidden(c.req.path, 'API key is suspended');
 *
 * // Use the low-level factory for custom problem types:
 * return ProblemResponse.create({
 *   type: 'https://adblock-compiler.jk-com.workers.dev/probs/custom',
 *   title: 'Custom Problem',
 *   status: 422,
 *   detail: 'The configuration contained an unsupported rule.',
 *   instance: '/api/compile',
 * });
 * ```
 *
 * @see {@link https://www.rfc-editor.org/rfc/rfc9457} RFC 9457
 * @see {@link https://blog.cloudflare.com/rfc-9457-agent-error-pages/} Cloudflare agent error pages
 * @module
 */

import type { ResponseOptions } from './response.ts';

// ── Content-Type ──────────────────────────────────────────────────────────────

/** Media type for RFC 9457 Problem Details responses. */
export const PROBLEM_CONTENT_TYPE = 'application/problem+json';

// ── Problem type URIs ─────────────────────────────────────────────────────────

/**
 * Base URI for well-known problem types served by this API.
 * Resolves to documentation that explains the error and remediation steps.
 */
export const PROBLEM_TYPE_BASE = 'https://adblock-compiler.jk-com.workers.dev/probs';

/** Well-known problem type URIs — one per distinct error class. */
export const PROBLEM_TYPES = {
    rateLimited: `${PROBLEM_TYPE_BASE}/rate-limited`,
    unauthorized: `${PROBLEM_TYPE_BASE}/unauthorized`,
    forbidden: `${PROBLEM_TYPE_BASE}/forbidden`,
    notFound: `${PROBLEM_TYPE_BASE}/not-found`,
    badRequest: `${PROBLEM_TYPE_BASE}/bad-request`,
    internalServerError: `${PROBLEM_TYPE_BASE}/internal-server-error`,
    serviceUnavailable: `${PROBLEM_TYPE_BASE}/service-unavailable`,
    gatewayTimeout: `${PROBLEM_TYPE_BASE}/gateway-timeout`,
    payloadTooLarge: `${PROBLEM_TYPE_BASE}/payload-too-large`,
    turnstileRejection: `${PROBLEM_TYPE_BASE}/turnstile-rejection`,
    adblockDetected: `${PROBLEM_TYPE_BASE}/adblock-detected`,
} as const satisfies Record<string, string>;

// ── ProblemDetails interface ──────────────────────────────────────────────────

/**
 * RFC 9457 Problem Details object.
 *
 * All fields except `type`, `title`, and `status` are optional extensions.
 * Consumers MUST NOT interpret absent fields as "no problem"; they should
 * rely on the `status` code and `type` URI for programmatic handling.
 *
 * @see {@link https://www.rfc-editor.org/rfc/rfc9457#section-3}
 */
export interface ProblemDetails {
    /**
     * A URI reference that identifies the problem type.
     * When dereferenced, it SHOULD provide human-readable documentation.
     * Use `'about:blank'` when no additional documentation is available.
     */
    type: string;

    /**
     * A short, human-readable summary of the problem type.
     * SHOULD NOT change across occurrences of the same problem type.
     */
    title: string;

    /** The HTTP status code generated by the origin server. */
    status: number;

    /**
     * A human-readable explanation specific to this occurrence of the problem.
     * MAY change across occurrences and SHOULD NOT be shown to end-users without
     * sanitisation.
     */
    detail?: string;

    /**
     * A URI reference that identifies the specific occurrence of the problem.
     * Typically the request path that triggered the error.
     */
    instance?: string;

    /** Extension members — any additional fields meaningful to the problem type. */
    [key: string]: unknown;
}

// ── Build helpers ─────────────────────────────────────────────────────────────

/**
 * Build a `Headers` object for a `application/problem+json` response.
 * Caller-supplied headers are merged first; `Content-Type` is always set last
 * so it cannot be accidentally overridden away from `application/problem+json`.
 */
function buildProblemHeaders(options: Omit<ResponseOptions, 'status'> = {}): Record<string, string> {
    const headers: Record<string, string> = {
        ...(options.headers ?? {}),
        'Content-Type': PROBLEM_CONTENT_TYPE,
    };
    return headers;
}

// ── ProblemResponse factory ───────────────────────────────────────────────────

/**
 * RFC 9457–compliant response factory.
 *
 * All methods return a `Response` with:
 *   - `Content-Type: application/problem+json`
 *   - A body that conforms to the `ProblemDetails` interface
 *   - The HTTP status code specified by the method or the `status` field
 *
 * Unlike {@link JsonResponse}, these methods do NOT wrap the body in a
 * `{ success: false, ... }` envelope.  The `status` field in the body carries
 * the same information and is part of the RFC 9457 contract.
 */
export const ProblemResponse = {
    /**
     * Create a Problem Details response from an explicit `ProblemDetails` object.
     * Use this for custom problem types not covered by the named factory methods.
     */
    create(
        problem: ProblemDetails,
        options: Omit<ResponseOptions, 'status'> = {},
    ): Response {
        const headers = buildProblemHeaders(options);
        return new Response(JSON.stringify(problem), {
            status: problem.status,
            headers,
        });
    },

    /**
     * 400 Bad Request — the request was malformed or failed schema validation.
     *
     * @param instance - The request path (used as the `instance` URI)
     * @param detail   - Optional human-readable explanation
     */
    badRequest(instance: string, detail?: string, options: Omit<ResponseOptions, 'status'> = {}): Response {
        return ProblemResponse.create({
            type: PROBLEM_TYPES.badRequest,
            title: 'Bad Request',
            status: 400,
            detail: detail ?? 'The request was malformed or failed validation.',
            instance,
        }, options);
    },

    /**
     * 401 Unauthorized — missing or invalid credentials.
     *
     * @param instance - The request path
     * @param detail   - Optional human-readable explanation
     */
    unauthorized(instance: string, detail?: string, options: Omit<ResponseOptions, 'status'> = {}): Response {
        return ProblemResponse.create({
            type: PROBLEM_TYPES.unauthorized,
            title: 'Unauthorized',
            status: 401,
            detail: detail ?? 'Authentication is required to access this resource.',
            instance,
        }, options);
    },

    /**
     * 403 Forbidden — the caller is authenticated but not authorised.
     *
     * @param instance - The request path
     * @param detail   - Optional human-readable explanation
     */
    forbidden(instance: string, detail?: string, options: Omit<ResponseOptions, 'status'> = {}): Response {
        return ProblemResponse.create({
            type: PROBLEM_TYPES.forbidden,
            title: 'Forbidden',
            status: 403,
            detail: detail ?? 'You do not have permission to access this resource.',
            instance,
        }, options);
    },

    /**
     * 403 Forbidden — Cloudflare Turnstile human-verification challenge failed.
     *
     * This specific variant is emitted when the Turnstile token is missing,
     * invalid, or could not be verified.  Clients (or adblockers) that see
     * this problem type should prompt the user to complete the CAPTCHA or
     * whitelist the site.
     *
     * @param instance - The request path
     * @param detail   - Optional reason from the Turnstile verification result
     */
    turnstileRejection(instance: string, detail?: string, options: Omit<ResponseOptions, 'status'> = {}): Response {
        return ProblemResponse.create({
            type: PROBLEM_TYPES.turnstileRejection,
            title: 'Turnstile Verification Failed',
            status: 403,
            detail: detail ?? 'The Cloudflare Turnstile challenge could not be verified. Complete the CAPTCHA or whitelist this site in your adblocker.',
            instance,
        }, options);
    },

    /**
     * 403 Forbidden — an adblocker or content-filter was detected blocking a
     * critical resource required for the API to function.
     *
     * @param instance - The resource path that was blocked
     * @param detail   - Optional description of the blocked resource
     */
    adblockDetected(instance: string, detail?: string, options: Omit<ResponseOptions, 'status'> = {}): Response {
        return ProblemResponse.create({
            type: PROBLEM_TYPES.adblockDetected,
            title: 'Adblock Detected',
            status: 403,
            detail: detail ?? 'A content-filtering extension is blocking a resource required by this API. Please whitelist this site or disable your adblocker.',
            instance,
        }, options);
    },

    /**
     * 404 Not Found — the requested resource does not exist.
     *
     * @param instance - The request path
     * @param detail   - Optional human-readable explanation
     */
    notFound(instance: string, detail?: string, options: Omit<ResponseOptions, 'status'> = {}): Response {
        return ProblemResponse.create({
            type: PROBLEM_TYPES.notFound,
            title: 'Not Found',
            status: 404,
            detail: detail ?? 'The requested resource could not be found.',
            instance,
        }, options);
    },

    /**
     * 413 Payload Too Large — request body exceeds the allowed limit.
     *
     * @param instance - The request path
     * @param detail   - Optional human-readable explanation
     */
    payloadTooLarge(instance: string, detail?: string, options: Omit<ResponseOptions, 'status'> = {}): Response {
        return ProblemResponse.create({
            type: PROBLEM_TYPES.payloadTooLarge,
            title: 'Payload Too Large',
            status: 413,
            detail: detail ?? 'The request body exceeded the maximum allowed size.',
            instance,
        }, options);
    },

    /**
     * 429 Too Many Requests — the caller has exceeded the rate limit.
     *
     * Sets the standard `Retry-After` header alongside the Problem Details body
     * so clients can back off correctly.
     *
     * @param instance        - The request path
     * @param retryAfterSecs  - Seconds until the rate limit window resets
     * @param detail          - Optional human-readable explanation
     */
    rateLimited(
        instance: string,
        retryAfterSecs: number,
        detail?: string,
        options: Omit<ResponseOptions, 'status'> = {},
    ): Response {
        return ProblemResponse.create({
            type: PROBLEM_TYPES.rateLimited,
            title: 'Too Many Requests',
            status: 429,
            detail: detail ?? `Rate limit exceeded. Please retry after ${retryAfterSecs} ${retryAfterSecs === 1 ? 'second' : 'seconds'}.`,
            instance,
            retryAfter: retryAfterSecs,
        }, {
            ...options,
            headers: {
                'Retry-After': String(retryAfterSecs),
                ...(options.headers ?? {}),
            },
        });
    },

    /**
     * 500 Internal Server Error — an unexpected server-side error occurred.
     *
     * @param instance  - The request path
     * @param requestId - Correlation ID for support / observability
     * @param detail    - Optional human-readable explanation (avoid leaking internals)
     */
    internalServerError(
        instance: string,
        requestId?: string,
        detail?: string,
        options: Omit<ResponseOptions, 'status'> = {},
    ): Response {
        return ProblemResponse.create({
            type: PROBLEM_TYPES.internalServerError,
            title: 'Internal Server Error',
            status: 500,
            detail: detail ?? 'An unexpected error occurred. Please try again later.',
            instance,
            ...(requestId ? { requestId } : {}),
        }, options);
    },

    /**
     * 503 Service Unavailable — the service is temporarily unavailable.
     *
     * @param instance - The request path
     * @param detail   - Optional human-readable explanation
     */
    serviceUnavailable(instance: string, detail?: string, options: Omit<ResponseOptions, 'status'> = {}): Response {
        return ProblemResponse.create({
            type: PROBLEM_TYPES.serviceUnavailable,
            title: 'Service Unavailable',
            status: 503,
            detail: detail ?? 'The service is temporarily unavailable. Please try again later.',
            instance,
        }, options);
    },

    /**
     * 504 Gateway Timeout — an upstream dependency (database, auth provider, etc.)
     * did not respond within the allowed time.
     *
     * @param instance - The request path
     * @param detail   - Optional human-readable explanation
     */
    gatewayTimeout(instance: string, detail?: string, options: Omit<ResponseOptions, 'status'> = {}): Response {
        return ProblemResponse.create({
            type: PROBLEM_TYPES.gatewayTimeout,
            title: 'Gateway Timeout',
            status: 504,
            detail: detail ?? 'An upstream dependency did not respond in time. Please try again.',
            instance,
        }, options);
    },
} as const;
