
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `LocalAuthUser` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model LocalAuthUser
 * 
 */
export type LocalAuthUserModel = runtime.Types.Result.DefaultSelection<Prisma.$LocalAuthUserPayload>

export type AggregateLocalAuthUser = {
  _count: LocalAuthUserCountAggregateOutputType | null
  _avg: LocalAuthUserAvgAggregateOutputType | null
  _sum: LocalAuthUserSumAggregateOutputType | null
  _min: LocalAuthUserMinAggregateOutputType | null
  _max: LocalAuthUserMaxAggregateOutputType | null
}

export type LocalAuthUserAvgAggregateOutputType = {
  apiDisabled: number | null
}

export type LocalAuthUserSumAggregateOutputType = {
  apiDisabled: number | null
}

export type LocalAuthUserMinAggregateOutputType = {
  id: string | null
  identifier: string | null
  identifierType: string | null
  passwordHash: string | null
  role: string | null
  tier: string | null
  apiDisabled: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type LocalAuthUserMaxAggregateOutputType = {
  id: string | null
  identifier: string | null
  identifierType: string | null
  passwordHash: string | null
  role: string | null
  tier: string | null
  apiDisabled: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type LocalAuthUserCountAggregateOutputType = {
  id: number
  identifier: number
  identifierType: number
  passwordHash: number
  role: number
  tier: number
  apiDisabled: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type LocalAuthUserAvgAggregateInputType = {
  apiDisabled?: true
}

export type LocalAuthUserSumAggregateInputType = {
  apiDisabled?: true
}

export type LocalAuthUserMinAggregateInputType = {
  id?: true
  identifier?: true
  identifierType?: true
  passwordHash?: true
  role?: true
  tier?: true
  apiDisabled?: true
  createdAt?: true
  updatedAt?: true
}

export type LocalAuthUserMaxAggregateInputType = {
  id?: true
  identifier?: true
  identifierType?: true
  passwordHash?: true
  role?: true
  tier?: true
  apiDisabled?: true
  createdAt?: true
  updatedAt?: true
}

export type LocalAuthUserCountAggregateInputType = {
  id?: true
  identifier?: true
  identifierType?: true
  passwordHash?: true
  role?: true
  tier?: true
  apiDisabled?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type LocalAuthUserAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which LocalAuthUser to aggregate.
   */
  where?: Prisma.LocalAuthUserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LocalAuthUsers to fetch.
   */
  orderBy?: Prisma.LocalAuthUserOrderByWithRelationInput | Prisma.LocalAuthUserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.LocalAuthUserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LocalAuthUsers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LocalAuthUsers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned LocalAuthUsers
  **/
  _count?: true | LocalAuthUserCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: LocalAuthUserAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: LocalAuthUserSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: LocalAuthUserMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: LocalAuthUserMaxAggregateInputType
}

export type GetLocalAuthUserAggregateType<T extends LocalAuthUserAggregateArgs> = {
      [P in keyof T & keyof AggregateLocalAuthUser]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateLocalAuthUser[P]>
    : Prisma.GetScalarType<T[P], AggregateLocalAuthUser[P]>
}




export type LocalAuthUserGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.LocalAuthUserWhereInput
  orderBy?: Prisma.LocalAuthUserOrderByWithAggregationInput | Prisma.LocalAuthUserOrderByWithAggregationInput[]
  by: Prisma.LocalAuthUserScalarFieldEnum[] | Prisma.LocalAuthUserScalarFieldEnum
  having?: Prisma.LocalAuthUserScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: LocalAuthUserCountAggregateInputType | true
  _avg?: LocalAuthUserAvgAggregateInputType
  _sum?: LocalAuthUserSumAggregateInputType
  _min?: LocalAuthUserMinAggregateInputType
  _max?: LocalAuthUserMaxAggregateInputType
}

export type LocalAuthUserGroupByOutputType = {
  id: string
  identifier: string
  identifierType: string
  passwordHash: string
  role: string
  tier: string
  apiDisabled: number
  createdAt: Date
  updatedAt: Date
  _count: LocalAuthUserCountAggregateOutputType | null
  _avg: LocalAuthUserAvgAggregateOutputType | null
  _sum: LocalAuthUserSumAggregateOutputType | null
  _min: LocalAuthUserMinAggregateOutputType | null
  _max: LocalAuthUserMaxAggregateOutputType | null
}

type GetLocalAuthUserGroupByPayload<T extends LocalAuthUserGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<LocalAuthUserGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof LocalAuthUserGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], LocalAuthUserGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], LocalAuthUserGroupByOutputType[P]>
      }
    >
  >



export type LocalAuthUserWhereInput = {
  AND?: Prisma.LocalAuthUserWhereInput | Prisma.LocalAuthUserWhereInput[]
  OR?: Prisma.LocalAuthUserWhereInput[]
  NOT?: Prisma.LocalAuthUserWhereInput | Prisma.LocalAuthUserWhereInput[]
  id?: Prisma.StringFilter<"LocalAuthUser"> | string
  identifier?: Prisma.StringFilter<"LocalAuthUser"> | string
  identifierType?: Prisma.StringFilter<"LocalAuthUser"> | string
  passwordHash?: Prisma.StringFilter<"LocalAuthUser"> | string
  role?: Prisma.StringFilter<"LocalAuthUser"> | string
  tier?: Prisma.StringFilter<"LocalAuthUser"> | string
  apiDisabled?: Prisma.IntFilter<"LocalAuthUser"> | number
  createdAt?: Prisma.DateTimeFilter<"LocalAuthUser"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"LocalAuthUser"> | Date | string
}

export type LocalAuthUserOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  identifier?: Prisma.SortOrder
  identifierType?: Prisma.SortOrder
  passwordHash?: Prisma.SortOrder
  role?: Prisma.SortOrder
  tier?: Prisma.SortOrder
  apiDisabled?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type LocalAuthUserWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  identifier?: string
  AND?: Prisma.LocalAuthUserWhereInput | Prisma.LocalAuthUserWhereInput[]
  OR?: Prisma.LocalAuthUserWhereInput[]
  NOT?: Prisma.LocalAuthUserWhereInput | Prisma.LocalAuthUserWhereInput[]
  identifierType?: Prisma.StringFilter<"LocalAuthUser"> | string
  passwordHash?: Prisma.StringFilter<"LocalAuthUser"> | string
  role?: Prisma.StringFilter<"LocalAuthUser"> | string
  tier?: Prisma.StringFilter<"LocalAuthUser"> | string
  apiDisabled?: Prisma.IntFilter<"LocalAuthUser"> | number
  createdAt?: Prisma.DateTimeFilter<"LocalAuthUser"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"LocalAuthUser"> | Date | string
}, "id" | "identifier">

export type LocalAuthUserOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  identifier?: Prisma.SortOrder
  identifierType?: Prisma.SortOrder
  passwordHash?: Prisma.SortOrder
  role?: Prisma.SortOrder
  tier?: Prisma.SortOrder
  apiDisabled?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.LocalAuthUserCountOrderByAggregateInput
  _avg?: Prisma.LocalAuthUserAvgOrderByAggregateInput
  _max?: Prisma.LocalAuthUserMaxOrderByAggregateInput
  _min?: Prisma.LocalAuthUserMinOrderByAggregateInput
  _sum?: Prisma.LocalAuthUserSumOrderByAggregateInput
}

export type LocalAuthUserScalarWhereWithAggregatesInput = {
  AND?: Prisma.LocalAuthUserScalarWhereWithAggregatesInput | Prisma.LocalAuthUserScalarWhereWithAggregatesInput[]
  OR?: Prisma.LocalAuthUserScalarWhereWithAggregatesInput[]
  NOT?: Prisma.LocalAuthUserScalarWhereWithAggregatesInput | Prisma.LocalAuthUserScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"LocalAuthUser"> | string
  identifier?: Prisma.StringWithAggregatesFilter<"LocalAuthUser"> | string
  identifierType?: Prisma.StringWithAggregatesFilter<"LocalAuthUser"> | string
  passwordHash?: Prisma.StringWithAggregatesFilter<"LocalAuthUser"> | string
  role?: Prisma.StringWithAggregatesFilter<"LocalAuthUser"> | string
  tier?: Prisma.StringWithAggregatesFilter<"LocalAuthUser"> | string
  apiDisabled?: Prisma.IntWithAggregatesFilter<"LocalAuthUser"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"LocalAuthUser"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"LocalAuthUser"> | Date | string
}

export type LocalAuthUserCreateInput = {
  id?: string
  identifier: string
  identifierType?: string
  passwordHash: string
  role?: string
  tier?: string
  apiDisabled?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type LocalAuthUserUncheckedCreateInput = {
  id?: string
  identifier: string
  identifierType?: string
  passwordHash: string
  role?: string
  tier?: string
  apiDisabled?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type LocalAuthUserUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  identifier?: Prisma.StringFieldUpdateOperationsInput | string
  identifierType?: Prisma.StringFieldUpdateOperationsInput | string
  passwordHash?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.StringFieldUpdateOperationsInput | string
  tier?: Prisma.StringFieldUpdateOperationsInput | string
  apiDisabled?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LocalAuthUserUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  identifier?: Prisma.StringFieldUpdateOperationsInput | string
  identifierType?: Prisma.StringFieldUpdateOperationsInput | string
  passwordHash?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.StringFieldUpdateOperationsInput | string
  tier?: Prisma.StringFieldUpdateOperationsInput | string
  apiDisabled?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LocalAuthUserCreateManyInput = {
  id?: string
  identifier: string
  identifierType?: string
  passwordHash: string
  role?: string
  tier?: string
  apiDisabled?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type LocalAuthUserUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  identifier?: Prisma.StringFieldUpdateOperationsInput | string
  identifierType?: Prisma.StringFieldUpdateOperationsInput | string
  passwordHash?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.StringFieldUpdateOperationsInput | string
  tier?: Prisma.StringFieldUpdateOperationsInput | string
  apiDisabled?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LocalAuthUserUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  identifier?: Prisma.StringFieldUpdateOperationsInput | string
  identifierType?: Prisma.StringFieldUpdateOperationsInput | string
  passwordHash?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.StringFieldUpdateOperationsInput | string
  tier?: Prisma.StringFieldUpdateOperationsInput | string
  apiDisabled?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LocalAuthUserCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  identifier?: Prisma.SortOrder
  identifierType?: Prisma.SortOrder
  passwordHash?: Prisma.SortOrder
  role?: Prisma.SortOrder
  tier?: Prisma.SortOrder
  apiDisabled?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type LocalAuthUserAvgOrderByAggregateInput = {
  apiDisabled?: Prisma.SortOrder
}

export type LocalAuthUserMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  identifier?: Prisma.SortOrder
  identifierType?: Prisma.SortOrder
  passwordHash?: Prisma.SortOrder
  role?: Prisma.SortOrder
  tier?: Prisma.SortOrder
  apiDisabled?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type LocalAuthUserMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  identifier?: Prisma.SortOrder
  identifierType?: Prisma.SortOrder
  passwordHash?: Prisma.SortOrder
  role?: Prisma.SortOrder
  tier?: Prisma.SortOrder
  apiDisabled?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type LocalAuthUserSumOrderByAggregateInput = {
  apiDisabled?: Prisma.SortOrder
}



export type LocalAuthUserSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  identifier?: boolean
  identifierType?: boolean
  passwordHash?: boolean
  role?: boolean
  tier?: boolean
  apiDisabled?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["localAuthUser"]>

export type LocalAuthUserSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  identifier?: boolean
  identifierType?: boolean
  passwordHash?: boolean
  role?: boolean
  tier?: boolean
  apiDisabled?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["localAuthUser"]>

export type LocalAuthUserSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  identifier?: boolean
  identifierType?: boolean
  passwordHash?: boolean
  role?: boolean
  tier?: boolean
  apiDisabled?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["localAuthUser"]>

export type LocalAuthUserSelectScalar = {
  id?: boolean
  identifier?: boolean
  identifierType?: boolean
  passwordHash?: boolean
  role?: boolean
  tier?: boolean
  apiDisabled?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type LocalAuthUserOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "identifier" | "identifierType" | "passwordHash" | "role" | "tier" | "apiDisabled" | "createdAt" | "updatedAt", ExtArgs["result"]["localAuthUser"]>

export type $LocalAuthUserPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "LocalAuthUser"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    identifier: string
    identifierType: string
    passwordHash: string
    role: string
    tier: string
    apiDisabled: number
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["localAuthUser"]>
  composites: {}
}

export type LocalAuthUserGetPayload<S extends boolean | null | undefined | LocalAuthUserDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$LocalAuthUserPayload, S>

export type LocalAuthUserCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<LocalAuthUserFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: LocalAuthUserCountAggregateInputType | true
  }

export interface LocalAuthUserDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['LocalAuthUser'], meta: { name: 'LocalAuthUser' } }
  /**
   * Find zero or one LocalAuthUser that matches the filter.
   * @param {LocalAuthUserFindUniqueArgs} args - Arguments to find a LocalAuthUser
   * @example
   * // Get one LocalAuthUser
   * const localAuthUser = await prisma.localAuthUser.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends LocalAuthUserFindUniqueArgs>(args: Prisma.SelectSubset<T, LocalAuthUserFindUniqueArgs<ExtArgs>>): Prisma.Prisma__LocalAuthUserClient<runtime.Types.Result.GetResult<Prisma.$LocalAuthUserPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one LocalAuthUser that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {LocalAuthUserFindUniqueOrThrowArgs} args - Arguments to find a LocalAuthUser
   * @example
   * // Get one LocalAuthUser
   * const localAuthUser = await prisma.localAuthUser.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends LocalAuthUserFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, LocalAuthUserFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__LocalAuthUserClient<runtime.Types.Result.GetResult<Prisma.$LocalAuthUserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first LocalAuthUser that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LocalAuthUserFindFirstArgs} args - Arguments to find a LocalAuthUser
   * @example
   * // Get one LocalAuthUser
   * const localAuthUser = await prisma.localAuthUser.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends LocalAuthUserFindFirstArgs>(args?: Prisma.SelectSubset<T, LocalAuthUserFindFirstArgs<ExtArgs>>): Prisma.Prisma__LocalAuthUserClient<runtime.Types.Result.GetResult<Prisma.$LocalAuthUserPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first LocalAuthUser that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LocalAuthUserFindFirstOrThrowArgs} args - Arguments to find a LocalAuthUser
   * @example
   * // Get one LocalAuthUser
   * const localAuthUser = await prisma.localAuthUser.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends LocalAuthUserFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, LocalAuthUserFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__LocalAuthUserClient<runtime.Types.Result.GetResult<Prisma.$LocalAuthUserPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more LocalAuthUsers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LocalAuthUserFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all LocalAuthUsers
   * const localAuthUsers = await prisma.localAuthUser.findMany()
   * 
   * // Get first 10 LocalAuthUsers
   * const localAuthUsers = await prisma.localAuthUser.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const localAuthUserWithIdOnly = await prisma.localAuthUser.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends LocalAuthUserFindManyArgs>(args?: Prisma.SelectSubset<T, LocalAuthUserFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LocalAuthUserPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a LocalAuthUser.
   * @param {LocalAuthUserCreateArgs} args - Arguments to create a LocalAuthUser.
   * @example
   * // Create one LocalAuthUser
   * const LocalAuthUser = await prisma.localAuthUser.create({
   *   data: {
   *     // ... data to create a LocalAuthUser
   *   }
   * })
   * 
   */
  create<T extends LocalAuthUserCreateArgs>(args: Prisma.SelectSubset<T, LocalAuthUserCreateArgs<ExtArgs>>): Prisma.Prisma__LocalAuthUserClient<runtime.Types.Result.GetResult<Prisma.$LocalAuthUserPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many LocalAuthUsers.
   * @param {LocalAuthUserCreateManyArgs} args - Arguments to create many LocalAuthUsers.
   * @example
   * // Create many LocalAuthUsers
   * const localAuthUser = await prisma.localAuthUser.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends LocalAuthUserCreateManyArgs>(args?: Prisma.SelectSubset<T, LocalAuthUserCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many LocalAuthUsers and returns the data saved in the database.
   * @param {LocalAuthUserCreateManyAndReturnArgs} args - Arguments to create many LocalAuthUsers.
   * @example
   * // Create many LocalAuthUsers
   * const localAuthUser = await prisma.localAuthUser.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many LocalAuthUsers and only return the `id`
   * const localAuthUserWithIdOnly = await prisma.localAuthUser.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends LocalAuthUserCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, LocalAuthUserCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LocalAuthUserPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a LocalAuthUser.
   * @param {LocalAuthUserDeleteArgs} args - Arguments to delete one LocalAuthUser.
   * @example
   * // Delete one LocalAuthUser
   * const LocalAuthUser = await prisma.localAuthUser.delete({
   *   where: {
   *     // ... filter to delete one LocalAuthUser
   *   }
   * })
   * 
   */
  delete<T extends LocalAuthUserDeleteArgs>(args: Prisma.SelectSubset<T, LocalAuthUserDeleteArgs<ExtArgs>>): Prisma.Prisma__LocalAuthUserClient<runtime.Types.Result.GetResult<Prisma.$LocalAuthUserPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one LocalAuthUser.
   * @param {LocalAuthUserUpdateArgs} args - Arguments to update one LocalAuthUser.
   * @example
   * // Update one LocalAuthUser
   * const localAuthUser = await prisma.localAuthUser.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends LocalAuthUserUpdateArgs>(args: Prisma.SelectSubset<T, LocalAuthUserUpdateArgs<ExtArgs>>): Prisma.Prisma__LocalAuthUserClient<runtime.Types.Result.GetResult<Prisma.$LocalAuthUserPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more LocalAuthUsers.
   * @param {LocalAuthUserDeleteManyArgs} args - Arguments to filter LocalAuthUsers to delete.
   * @example
   * // Delete a few LocalAuthUsers
   * const { count } = await prisma.localAuthUser.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends LocalAuthUserDeleteManyArgs>(args?: Prisma.SelectSubset<T, LocalAuthUserDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more LocalAuthUsers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LocalAuthUserUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many LocalAuthUsers
   * const localAuthUser = await prisma.localAuthUser.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends LocalAuthUserUpdateManyArgs>(args: Prisma.SelectSubset<T, LocalAuthUserUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more LocalAuthUsers and returns the data updated in the database.
   * @param {LocalAuthUserUpdateManyAndReturnArgs} args - Arguments to update many LocalAuthUsers.
   * @example
   * // Update many LocalAuthUsers
   * const localAuthUser = await prisma.localAuthUser.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more LocalAuthUsers and only return the `id`
   * const localAuthUserWithIdOnly = await prisma.localAuthUser.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends LocalAuthUserUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, LocalAuthUserUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LocalAuthUserPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one LocalAuthUser.
   * @param {LocalAuthUserUpsertArgs} args - Arguments to update or create a LocalAuthUser.
   * @example
   * // Update or create a LocalAuthUser
   * const localAuthUser = await prisma.localAuthUser.upsert({
   *   create: {
   *     // ... data to create a LocalAuthUser
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the LocalAuthUser we want to update
   *   }
   * })
   */
  upsert<T extends LocalAuthUserUpsertArgs>(args: Prisma.SelectSubset<T, LocalAuthUserUpsertArgs<ExtArgs>>): Prisma.Prisma__LocalAuthUserClient<runtime.Types.Result.GetResult<Prisma.$LocalAuthUserPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of LocalAuthUsers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LocalAuthUserCountArgs} args - Arguments to filter LocalAuthUsers to count.
   * @example
   * // Count the number of LocalAuthUsers
   * const count = await prisma.localAuthUser.count({
   *   where: {
   *     // ... the filter for the LocalAuthUsers we want to count
   *   }
   * })
  **/
  count<T extends LocalAuthUserCountArgs>(
    args?: Prisma.Subset<T, LocalAuthUserCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], LocalAuthUserCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a LocalAuthUser.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LocalAuthUserAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends LocalAuthUserAggregateArgs>(args: Prisma.Subset<T, LocalAuthUserAggregateArgs>): Prisma.PrismaPromise<GetLocalAuthUserAggregateType<T>>

  /**
   * Group by LocalAuthUser.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LocalAuthUserGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends LocalAuthUserGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: LocalAuthUserGroupByArgs['orderBy'] }
      : { orderBy?: LocalAuthUserGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, LocalAuthUserGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetLocalAuthUserGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the LocalAuthUser model
 */
readonly fields: LocalAuthUserFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for LocalAuthUser.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__LocalAuthUserClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the LocalAuthUser model
 */
export interface LocalAuthUserFieldRefs {
  readonly id: Prisma.FieldRef<"LocalAuthUser", 'String'>
  readonly identifier: Prisma.FieldRef<"LocalAuthUser", 'String'>
  readonly identifierType: Prisma.FieldRef<"LocalAuthUser", 'String'>
  readonly passwordHash: Prisma.FieldRef<"LocalAuthUser", 'String'>
  readonly role: Prisma.FieldRef<"LocalAuthUser", 'String'>
  readonly tier: Prisma.FieldRef<"LocalAuthUser", 'String'>
  readonly apiDisabled: Prisma.FieldRef<"LocalAuthUser", 'Int'>
  readonly createdAt: Prisma.FieldRef<"LocalAuthUser", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"LocalAuthUser", 'DateTime'>
}
    

// Custom InputTypes
/**
 * LocalAuthUser findUnique
 */
export type LocalAuthUserFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LocalAuthUser
   */
  select?: Prisma.LocalAuthUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LocalAuthUser
   */
  omit?: Prisma.LocalAuthUserOmit<ExtArgs> | null
  /**
   * Filter, which LocalAuthUser to fetch.
   */
  where: Prisma.LocalAuthUserWhereUniqueInput
}

/**
 * LocalAuthUser findUniqueOrThrow
 */
export type LocalAuthUserFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LocalAuthUser
   */
  select?: Prisma.LocalAuthUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LocalAuthUser
   */
  omit?: Prisma.LocalAuthUserOmit<ExtArgs> | null
  /**
   * Filter, which LocalAuthUser to fetch.
   */
  where: Prisma.LocalAuthUserWhereUniqueInput
}

/**
 * LocalAuthUser findFirst
 */
export type LocalAuthUserFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LocalAuthUser
   */
  select?: Prisma.LocalAuthUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LocalAuthUser
   */
  omit?: Prisma.LocalAuthUserOmit<ExtArgs> | null
  /**
   * Filter, which LocalAuthUser to fetch.
   */
  where?: Prisma.LocalAuthUserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LocalAuthUsers to fetch.
   */
  orderBy?: Prisma.LocalAuthUserOrderByWithRelationInput | Prisma.LocalAuthUserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for LocalAuthUsers.
   */
  cursor?: Prisma.LocalAuthUserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LocalAuthUsers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LocalAuthUsers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LocalAuthUsers.
   */
  distinct?: Prisma.LocalAuthUserScalarFieldEnum | Prisma.LocalAuthUserScalarFieldEnum[]
}

/**
 * LocalAuthUser findFirstOrThrow
 */
export type LocalAuthUserFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LocalAuthUser
   */
  select?: Prisma.LocalAuthUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LocalAuthUser
   */
  omit?: Prisma.LocalAuthUserOmit<ExtArgs> | null
  /**
   * Filter, which LocalAuthUser to fetch.
   */
  where?: Prisma.LocalAuthUserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LocalAuthUsers to fetch.
   */
  orderBy?: Prisma.LocalAuthUserOrderByWithRelationInput | Prisma.LocalAuthUserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for LocalAuthUsers.
   */
  cursor?: Prisma.LocalAuthUserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LocalAuthUsers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LocalAuthUsers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LocalAuthUsers.
   */
  distinct?: Prisma.LocalAuthUserScalarFieldEnum | Prisma.LocalAuthUserScalarFieldEnum[]
}

/**
 * LocalAuthUser findMany
 */
export type LocalAuthUserFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LocalAuthUser
   */
  select?: Prisma.LocalAuthUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LocalAuthUser
   */
  omit?: Prisma.LocalAuthUserOmit<ExtArgs> | null
  /**
   * Filter, which LocalAuthUsers to fetch.
   */
  where?: Prisma.LocalAuthUserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LocalAuthUsers to fetch.
   */
  orderBy?: Prisma.LocalAuthUserOrderByWithRelationInput | Prisma.LocalAuthUserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing LocalAuthUsers.
   */
  cursor?: Prisma.LocalAuthUserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LocalAuthUsers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LocalAuthUsers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LocalAuthUsers.
   */
  distinct?: Prisma.LocalAuthUserScalarFieldEnum | Prisma.LocalAuthUserScalarFieldEnum[]
}

/**
 * LocalAuthUser create
 */
export type LocalAuthUserCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LocalAuthUser
   */
  select?: Prisma.LocalAuthUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LocalAuthUser
   */
  omit?: Prisma.LocalAuthUserOmit<ExtArgs> | null
  /**
   * The data needed to create a LocalAuthUser.
   */
  data: Prisma.XOR<Prisma.LocalAuthUserCreateInput, Prisma.LocalAuthUserUncheckedCreateInput>
}

/**
 * LocalAuthUser createMany
 */
export type LocalAuthUserCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many LocalAuthUsers.
   */
  data: Prisma.LocalAuthUserCreateManyInput | Prisma.LocalAuthUserCreateManyInput[]
}

/**
 * LocalAuthUser createManyAndReturn
 */
export type LocalAuthUserCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LocalAuthUser
   */
  select?: Prisma.LocalAuthUserSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the LocalAuthUser
   */
  omit?: Prisma.LocalAuthUserOmit<ExtArgs> | null
  /**
   * The data used to create many LocalAuthUsers.
   */
  data: Prisma.LocalAuthUserCreateManyInput | Prisma.LocalAuthUserCreateManyInput[]
}

/**
 * LocalAuthUser update
 */
export type LocalAuthUserUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LocalAuthUser
   */
  select?: Prisma.LocalAuthUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LocalAuthUser
   */
  omit?: Prisma.LocalAuthUserOmit<ExtArgs> | null
  /**
   * The data needed to update a LocalAuthUser.
   */
  data: Prisma.XOR<Prisma.LocalAuthUserUpdateInput, Prisma.LocalAuthUserUncheckedUpdateInput>
  /**
   * Choose, which LocalAuthUser to update.
   */
  where: Prisma.LocalAuthUserWhereUniqueInput
}

/**
 * LocalAuthUser updateMany
 */
export type LocalAuthUserUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update LocalAuthUsers.
   */
  data: Prisma.XOR<Prisma.LocalAuthUserUpdateManyMutationInput, Prisma.LocalAuthUserUncheckedUpdateManyInput>
  /**
   * Filter which LocalAuthUsers to update
   */
  where?: Prisma.LocalAuthUserWhereInput
  /**
   * Limit how many LocalAuthUsers to update.
   */
  limit?: number
}

/**
 * LocalAuthUser updateManyAndReturn
 */
export type LocalAuthUserUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LocalAuthUser
   */
  select?: Prisma.LocalAuthUserSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the LocalAuthUser
   */
  omit?: Prisma.LocalAuthUserOmit<ExtArgs> | null
  /**
   * The data used to update LocalAuthUsers.
   */
  data: Prisma.XOR<Prisma.LocalAuthUserUpdateManyMutationInput, Prisma.LocalAuthUserUncheckedUpdateManyInput>
  /**
   * Filter which LocalAuthUsers to update
   */
  where?: Prisma.LocalAuthUserWhereInput
  /**
   * Limit how many LocalAuthUsers to update.
   */
  limit?: number
}

/**
 * LocalAuthUser upsert
 */
export type LocalAuthUserUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LocalAuthUser
   */
  select?: Prisma.LocalAuthUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LocalAuthUser
   */
  omit?: Prisma.LocalAuthUserOmit<ExtArgs> | null
  /**
   * The filter to search for the LocalAuthUser to update in case it exists.
   */
  where: Prisma.LocalAuthUserWhereUniqueInput
  /**
   * In case the LocalAuthUser found by the `where` argument doesn't exist, create a new LocalAuthUser with this data.
   */
  create: Prisma.XOR<Prisma.LocalAuthUserCreateInput, Prisma.LocalAuthUserUncheckedCreateInput>
  /**
   * In case the LocalAuthUser was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.LocalAuthUserUpdateInput, Prisma.LocalAuthUserUncheckedUpdateInput>
}

/**
 * LocalAuthUser delete
 */
export type LocalAuthUserDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LocalAuthUser
   */
  select?: Prisma.LocalAuthUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LocalAuthUser
   */
  omit?: Prisma.LocalAuthUserOmit<ExtArgs> | null
  /**
   * Filter which LocalAuthUser to delete.
   */
  where: Prisma.LocalAuthUserWhereUniqueInput
}

/**
 * LocalAuthUser deleteMany
 */
export type LocalAuthUserDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which LocalAuthUsers to delete
   */
  where?: Prisma.LocalAuthUserWhereInput
  /**
   * Limit how many LocalAuthUsers to delete.
   */
  limit?: number
}

/**
 * LocalAuthUser without action
 */
export type LocalAuthUserDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LocalAuthUser
   */
  select?: Prisma.LocalAuthUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LocalAuthUser
   */
  omit?: Prisma.LocalAuthUserOmit<ExtArgs> | null
}
