$kind: http-request
description: >
  Lists all saved configurations for the authenticated user.
url: {{baseUrl}}/configuration/saved
method: GET
headers:
  Accept: application/json
  X-API-Key: "{{apiKey}}"
body:
  type: text
  content: ""
examples: ./.resources/List saved configurations.resources/examples
order: 6000
