#!/usr/bin/env python3
"""
auth-healthcheck.py — Better Auth / adblock-compiler production auth diagnostic

Checks:
  1.  API reachability + version
  2.  Better Auth sign-up
  3.  Better Auth sign-in + token extraction
  4.  Session validation via Bearer token
  5.  Email verification state
  6.  Better Auth KV (wrangler kv key list)
  7.  D1 databases (wrangler d1 execute --remote)
  8.  Neon / PostgreSQL table row counts + user/session presence
  9.  Better Auth admin API (optional)
  10. Wrangler tail log summary (background process)

Modes (--mode flag or interactive menu when stdin is a TTY):
  all             Run all checks  (default in pipelines / CI)
  checks          Run checks only — do not clean up test data
  cleanup         Delete test data only — skip checks
  checks-cleanup  Run checks then delete test data

Config:
  cp tools/auth-healthcheck.env.example tools/auth-healthcheck.env
  # Set NEON_URL at minimum

Logs / reports are written to tools/logs/

Requirements:
  python3 -m venv tools/.venv
  source tools/.venv/bin/activate
  pip install requests rich psycopg2-binary

Exit codes (for pipeline chaining):
  0   All checks passed (or cleanup-only with no errors)
  1   One or more checks FAILED
"""

import argparse
import json
import os
import re
import subprocess
import sys
import time
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import IO

# ── dependency check ───────────────────────────────────────────────
missing = []
for pkg in ("requests", "rich", "psycopg2"):
    try:
        __import__(pkg)
    except ImportError:
        missing.append(pkg if pkg != "psycopg2" else "psycopg2-binary")
if missing:
    print(f"Missing packages: {', '.join(missing)}")
    print(f"Run: pip install {' '.join(missing)}")
    sys.exit(1)

import requests
import psycopg2
import psycopg2.sql
from rich.console import Console
from rich.panel import Panel

console = Console()


# ============================================================================
# Config loader
# ============================================================================

def _find_repo_root() -> Path:
    here = Path(__file__).resolve().parent
    for candidate in [here, *here.parents]:
        if (candidate / "wrangler.toml").exists():
            return candidate
    cwd = Path.cwd()
    for candidate in [cwd, *cwd.parents]:
        if (candidate / "wrangler.toml").exists():
            return candidate
    return here


def _load_env_file(path: Path) -> dict[str, str]:
    result: dict[str, str] = {}
    if not path.exists():
        return result
    with open(path) as f:
        for raw in f:
            line = raw.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, _, val = line.partition("=")
            val = val.strip()
            if len(val) >= 2 and val[0] in ('"', "'") and val[-1] == val[0]:
                val = val[1:-1]
            result[key.strip()] = val
    return result


def _load_config() -> dict:
    repo_root = _find_repo_root()
    env_file  = repo_root / "tools" / "auth-healthcheck.env"
    file_env  = _load_env_file(env_file)

    # Ensure logs directory exists
    logs_dir = repo_root / "tools" / "logs"
    logs_dir.mkdir(parents=True, exist_ok=True)

    if env_file.exists():
        console.print(f"[dim]\U0001f4c4 Config : {env_file}[/dim]")
    else:
        console.print(
            f"[yellow]\u26a0\ufe0f  Config file not found: {env_file}[/yellow]\n"
            "   Run: cp tools/auth-healthcheck.env.example tools/auth-healthcheck.env"
        )

    def get(key: str, default: str = "") -> str:
        for src in (file_env.get(key, ""), os.environ.get(key, "")):
            if src and "<" not in src:
                return src
        return default

    # Print a startup banner showing per-key status.
    # Tuple fields: (env key, "optional"|"required", default label or "" if none)
    _important_keys = [
        ("API_BASE",            "optional", "https://api.bloqr.dev/api"),
        ("TEST_EMAIL",          "optional", "<auto-generated>"),
        ("TEST_PASSWORD",       "optional", "<default>"),
        ("TEST_NAME",           "optional", "<default>"),
        ("NEON_URL",            "optional", ""),
        ("BETTER_AUTH_API_KEY", "optional", ""),
        ("KV_BINDING",          "optional", "BETTER_AUTH_KV"),
        ("D1_BINDING",          "optional", "DB"),
        ("D1_ADMIN_BINDING",    "optional", "ADMIN_DB"),
        ("WRANGLER_ENV",        "optional", ""),
        ("ENABLE_TAIL",         "optional", "true"),
        ("TAIL_WAIT_SEC",       "optional", "4"),
    ]
    _sensitive_keys = {"TEST_PASSWORD", "BETTER_AUTH_API_KEY", "NEON_URL"}
    _SENSITIVE_PREFIX_LEN = 6
    _MAX_DISPLAY_LEN = 80
    for key, requiredness, default in _important_keys:
        val = file_env.get(key, "") or os.environ.get(key, "")
        if val and "<" not in val:
            if key in _sensitive_keys:
                display = val[:_SENSITIVE_PREFIX_LEN] + "\u2026"
            else:
                display = val[:_MAX_DISPLAY_LEN] + "\u2026" if len(val) > _MAX_DISPLAY_LEN else val
            console.print(f"[dim]  \u2713 {key} = {display}[/dim]")
        elif default:
            console.print(f"[dim]  \u00b7 {key} = {default} (default)[/dim]")
        elif requiredness == "required":
            console.print(f"[yellow]  ! {key} \u2014 required, not set[/yellow]")
        else:
            console.print(f"[dim]  \u00b7 {key} \u2014 not set[/dim]")

    raw_email  = get("TEST_EMAIL", "")
    test_email = raw_email or f"healthcheck-{uuid.uuid4().hex[:8]}@bloqr.dev"
    neon_url   = get("NEON_URL", "")

    if neon_url:
        masked = neon_url[:35] + "..." if len(neon_url) > 35 else neon_url
        console.print(f"[dim]\U0001f517 NEON_URL: {masked}[/dim]")
    else:
        rf, re_ = file_env.get("NEON_URL", ""), os.environ.get("NEON_URL", "")
        if rf and "<" in rf:
            console.print("[yellow]\u26a0\ufe0f  NEON_URL in env file still has placeholder text[/yellow]")
        elif re_ and "<" in re_:
            console.print("[yellow]\u26a0\ufe0f  NEON_URL shell var has placeholder text[/yellow]")
        else:
            console.print(
                "[yellow]\u26a0\ufe0f  NEON_URL not set \u2014 Neon checks will be skipped[/yellow]\n"
                "   export NEON_URL='postgresql://user:pass@host.neon.tech/db?sslmode=require'"
            )

    ts = datetime.now().strftime("%Y%m%d-%H%M%S")
    return {
        "repo_root":           repo_root,
        "logs_dir":            logs_dir,
        "api_base":            get("API_BASE",            "https://api.bloqr.dev/api"),
        "test_email":          test_email,
        "test_password":       get("TEST_PASSWORD",       "HealthCheck1234!!@@"),
        "test_name":           get("TEST_NAME",           "Auth Healthcheck Bot"),
        "neon_url":            neon_url,
        "better_auth_api_key": get("BETTER_AUTH_API_KEY", ""),
        "kv_binding":          get("KV_BINDING",          "BETTER_AUTH_KV"),
        "d1_binding":          get("D1_BINDING",          "DB"),
        "d1_admin_binding":    get("D1_ADMIN_BINDING",    "ADMIN_DB"),
        "wrangler_env":        get("WRANGLER_ENV",        ""),
        "enable_tail":         get("ENABLE_TAIL",         "true").lower() == "true",
        "tail_wait_sec":       int(get("TAIL_WAIT_SEC",   "4")),
        "tail_log_file":       str(logs_dir / f"wrangler-tail-{ts}.log"),
        "report_file":         str(logs_dir / f"auth-healthcheck-{ts}.json"),
    }


# ============================================================================
# State
# ============================================================================

CONFIG: dict = {}
report: dict = {
    "timestamp": datetime.now().isoformat(),
    "results":   {},
    "errors":    [],
    "summary":   {"passed": 0, "failed": 0, "warnings": 0},
}
_tail_proc: subprocess.Popen | None = None
_tail_file: IO[str] | None = None  # file handle for wrangler tail stdout
_neon_table_cache: dict | None = None
# Regex for safe (no SQL-injection risk) PostgreSQL table names from discovery.
_SAFE_TABLE_NAME_RE = re.compile(r'^[A-Za-z0-9_]+$')


# ============================================================================
# Helpers
# ============================================================================

def _record(name: str, status: str, detail: str, data: dict | None = None) -> None:
    icons  = {"PASS": "\u2705", "FAIL": "\u274c", "WARN": "\u26a0\ufe0f "}
    colors = {"PASS": "green",  "FAIL": "red",   "WARN": "yellow"}
    c = colors.get(status, "white")
    console.print(f"  {icons.get(status, '\u2022')} [{c}]{name}[/{c}]: {detail}")
    report["results"][name] = {"status": status, "detail": detail, "data": data or {}}
    report["summary"][{"PASS": "passed", "FAIL": "failed", "WARN": "warnings"}[status]] += 1


def ok(name: str, detail: str = "", data: dict | None = None)   -> None: _record(name, "PASS", detail, data)
def fail(name: str, detail: str = "", data: dict | None = None) -> None:
    _record(name, "FAIL", detail, data)
    report["errors"].append({"check": name, "detail": detail})
def warn(name: str, detail: str = "", data: dict | None = None) -> None: _record(name, "WARN", detail, data)


def section(title: str) -> None:
    console.print()
    console.rule(f"[bold cyan]{title}[/bold cyan]")


def wrangler(*args: str, timeout: int = 30) -> tuple[bool, str, str]:
    """
    Run a wrangler command.
    Returns (success, stdout, stderr)  — kept separate so callers can
    parse JSON from stdout without warnings from stderr polluting it.
    """
    cmd = ["wrangler", *args]
    if CONFIG.get("wrangler_env"):
        cmd += ["--env", CONFIG["wrangler_env"]]
    try:
        r = subprocess.run(
            cmd, capture_output=True, text=True,
            timeout=timeout, cwd=str(CONFIG["repo_root"]),
        )
        stdout = r.stdout.strip()
        stderr = r.stderr.strip()
        # Wrangler 4.x exits 1 on benign wrangler.toml warnings even when the
        # command succeeded.  Treat as success if stdout has content and stderr
        # is only known-benign lines.
        _BENIGN = ("execution_model", "Unexpected fields", "Processing wrangler.toml",
                   "wrangler ", "▲", "WARNING", "---", "⛅")
        stderr_only_benign = all(
            any(pat in line for pat in _BENIGN) or not line.strip()
            for line in stderr.splitlines()
        )
        success = (r.returncode == 0) or (stderr_only_benign and bool(stdout))
        return success, stdout, stderr
    except subprocess.TimeoutExpired:
        return False, "", f"timeout after {timeout}s"
    except FileNotFoundError:
        return False, "", "wrangler not found — is it installed and on PATH?"


def _extract_json(text: str) -> str:
    """Strip ANSI codes, then return the full substring starting at the first JSON bracket.

    Returning only the first line would break multi-line pretty-printed arrays/objects
    (e.g. wrangler outputs ``[\n  {\n    "name": ...``).  We always slice from the first
    ``[`` or ``{`` to the end of the cleaned string so that ``json.loads()`` receives the
    complete value regardless of indentation.
    """
    clean = re.sub(r'\x1b\[[0-9;]*[mK]', '', text)
    best_idx = -1
    for ch in ('[', '{'):
        idx = clean.find(ch)
        if idx >= 0 and (best_idx < 0 or idx < best_idx):
            best_idx = idx
    return clean[best_idx:] if best_idx >= 0 else ''


# ============================================================================
# Tail log
# ============================================================================

def start_tail() -> None:
    global _tail_proc
    global _tail_file
    if not CONFIG["enable_tail"]:
        return
    try:
        _tail_file = open(CONFIG["tail_log_file"], "w", encoding="utf-8")
        try:
            _tail_proc = subprocess.Popen(
                ["wrangler", "tail", "--format", "json"],
                stdout=_tail_file,
                stderr=subprocess.DEVNULL,
                cwd=str(CONFIG["repo_root"]),
            )
        except Exception:
            _tail_file.close()
            _tail_file = None
            raise
        tail_log_abs = Path(CONFIG["tail_log_file"]).resolve()
        console.print(f"[dim]\U0001f4e1 wrangler tail started (PID {_tail_proc.pid})[/dim]")
        console.print(f"[dim]\U0001f4dd Tail log \u2192 {tail_log_abs}[/dim]")
    except Exception as e:
        console.print(f"[yellow]\u26a0\ufe0f  Could not start wrangler tail: {e}[/yellow]")


def stop_tail() -> None:
    """Terminate tail process and close the log file handle."""
    global _tail_proc
    global _tail_file
    if _tail_proc:
        try:
            _tail_proc.terminate()
        except (ProcessLookupError, OSError):
            pass
        try:
            _tail_proc.wait(timeout=3)
        except subprocess.TimeoutExpired:
            _tail_proc.kill()
            try:
                _tail_proc.wait(timeout=3)
            except subprocess.TimeoutExpired:
                pass
        _tail_proc = None
    if _tail_file:
        try:
            _tail_file.flush()
            _tail_file.close()
        except Exception:
            pass
        _tail_file = None


# ============================================================================
# Checks
# ============================================================================

def check_api() -> None:
    section("1 \u00b7 API Health")
    for path, label in [("/version", "GET /version"), ("/auth/providers", "GET /auth/providers")]:
        try:
            r = requests.get(f"{CONFIG['api_base']}{path}", timeout=10)
            d = r.json() if "application/json" in r.headers.get("content-type", "") else {}
            if r.ok:
                extra = f"version={d.get('version','?')}" if "version" in d else f"HTTP {r.status_code}"
                ok(label, extra, d)
            else:
                fail(label, f"HTTP {r.status_code}: {r.text[:120]}")
        except Exception as e:
            fail(label, str(e))


def _verify_email_in_neon(user_id: str) -> bool:
    """Set emailVerified on the test user row in Neon so sign-in won't be blocked."""
    neon_url = CONFIG["neon_url"]
    if not neon_url:
        console.print("[yellow]\u26a0\ufe0f  NEON_URL not set \u2014 cannot pre-verify email, sign-in will likely fail[/yellow]")
        return False
    try:
        conn = psycopg2.connect(neon_url, connect_timeout=10)
        conn.autocommit = True
        cur = conn.cursor()
        tbl_map = _discover_neon_tables(cur)
        user_tbl = tbl_map.get("user")
        if not user_tbl:
            console.print(f"[yellow]\u26a0\ufe0f  Cannot pre-verify: no user table found (discovered: {list(tbl_map.values())})[/yellow]")
            cur.close()
            conn.close()
            return False
        # Better Auth stores emailVerified as a timestamptz column; fall back to boolean
        verified = False
        for val in (datetime.now(timezone.utc), True):
            try:
                cur.execute(
                    f'UPDATE "{user_tbl}" SET "emailVerified" = %s WHERE id = %s',
                    (val, user_id),
                )
                verified = True
                break
            except Exception:
                conn.rollback()
                continue
        cur.close()
        conn.close()
        if verified:
            console.print(f"[dim]\U0001f4e7 emailVerified set in Neon for {user_id[:8]}\u2026[/dim]")
        return verified
    except Exception as e:
        console.print(f"[yellow]\u26a0\ufe0f  Could not pre-verify email in Neon: {e}[/yellow]")
        return False


def _auto_verify_email(email: str) -> None:
    """Directly mark the test user's email as verified in Neon by email address.

    Tries ``"emailVerified"`` (camelCase, Better Auth ≥1.x) then
    ``"email_verified"`` (snake_case, older schemas) so it works regardless
    of column naming convention. Called immediately after a successful sign-up.
    """
    neon_url = CONFIG.get("neon_url")
    if not neon_url:
        return
    try:
        conn = psycopg2.connect(neon_url, connect_timeout=10)
        conn.autocommit = True
        cur = conn.cursor()
        tbl_map = _discover_neon_tables(cur)
        user_tbl = tbl_map.get("user", "users")
        for col in ("emailVerified", "email_verified"):
            try:
                cur.execute(
                    psycopg2.sql.SQL("UPDATE {} SET {} = NOW() WHERE email = %s").format(
                        psycopg2.sql.Identifier(user_tbl),
                        psycopg2.sql.Identifier(col),
                    ),
                    (email,),
                )
                if not conn.autocommit:
                    conn.commit()
                if cur.rowcount > 0:
                    console.print(f"[dim]  \u2713 emailVerified set for {email}[/dim]")
                    break
            except psycopg2.errors.UndefinedColumn:  # type: ignore[attr-defined]
                conn.rollback()
        cur.close()
        conn.close()
    except Exception as e:
        console.print(f"[yellow]\u26a0\ufe0f  auto-verify email failed: {e}[/yellow]")


def check_signup() -> dict | None:
    section("2 \u00b7 Sign-Up")
    if CONFIG.get("dry_run"):
        warn("POST /auth/sign-up/email", "Skipped \u2014 dry-run mode")
        return None
    try:
        r = requests.post(
            f"{CONFIG['api_base']}/auth/sign-up/email",
            json={"name": CONFIG["test_name"], "email": CONFIG["test_email"], "password": CONFIG["test_password"]},
            timeout=20,
        )
        d = r.json() if "application/json" in r.headers.get("content-type", "") else {}
        if r.status_code in (200, 201):
            uid = (d.get("user") or {}).get("id", "?")
            ok("POST /auth/sign-up/email", f"HTTP {r.status_code} \u2014 user_id={uid}", d)
            if uid and uid != "?":
                CONFIG["_created_user_id"] = uid
                CONFIG["email_verified_via_neon"] = _verify_email_in_neon(uid)
                _auto_verify_email(CONFIG["test_email"])
                # Brief pause so the emailVerified write propagates to Neon's
                # read replicas before check_signin() immediately queries them.
                time.sleep(1)
            return d
        elif r.status_code == 422 and "already" in r.text.lower():
            warn("POST /auth/sign-up/email", "User already exists \u2014 will attempt sign-in")
            return None
        else:
            fail("POST /auth/sign-up/email", f"HTTP {r.status_code}: {r.text[:300]}", d)
            return None
    except Exception as e:
        fail("POST /auth/sign-up/email", str(e))
        return None


def check_signin(signup_result: dict | None, signup_succeeded: bool = False) -> dict | None:
    section("3 \u00b7 Sign-In + Token")
    if CONFIG.get("dry_run"):
        warn("POST /auth/sign-in/email", "Skipped \u2014 dry-run mode")
        return None
    # Small delay so the sign-up write propagates before we sign in
    time.sleep(2)
    try:
        r = requests.post(
            f"{CONFIG['api_base']}/auth/sign-in/email",
            json={"email": CONFIG["test_email"], "password": CONFIG["test_password"]},
            timeout=20,
        )
        d = r.json() if "application/json" in r.headers.get("content-type", "") else {}
        if r.status_code != 200:
            if r.status_code == 401:
                # Downgrade to WARN only when the response signals an email-verification
                # block, or when this run just created the user (so it's a fresh, unverified
                # account).  Any other 401 (wrong password, stale credential, etc.) stays FAIL.
                body_lower = r.text.lower()
                is_email_verification_error = (
                    "verif" in body_lower
                    or "email_not_verified" in body_lower
                    or (d.get("code") or "").upper() == "EMAIL_NOT_VERIFIED"
                )
                if is_email_verification_error or signup_succeeded:
                    if signup_succeeded:
                        hint = "User was just created in this run \u2014 likely awaiting email verification."
                    else:
                        hint = "Response indicates email verification is required."
                    msg = (
                        f"HTTP 401 \u2014 sign-in blocked. {hint} "
                        "Check requireEmailVerification in Better Auth config or use a pre-verified test user."
                    )
                    warn("POST /auth/sign-in/email", msg, d)
                else:
                    fail("POST /auth/sign-in/email", f"HTTP 401: {r.text[:400]}", d)
            else:
                fail("POST /auth/sign-in/email", f"HTTP {r.status_code}: {r.text[:400]}", d)
            return None

        ok("POST /auth/sign-in/email", "HTTP 200 OK")
        token   = (d.get("session") or {}).get("token") or d.get("token")
        session = d.get("session") or {}
        user    = d.get("user")    or {}

        (ok if token else fail)("session.token present",
            f"{token[:24]}\u2026" if token else f"missing \u2014 keys: {list(d.keys())}", d)
        (ok if user.get("id") else fail)("user object",
            f"id={user.get('id')}  email={user.get('email')}  tier={user.get('tier','?')}  role={user.get('role','?')}" if user.get("id") else f"no user.id \u2014 keys: {list(user.keys())}", d)
        (ok if session.get("id") else fail)("session object",
            f"id={str(session.get('id',''))[:20]}\u2026  expires={session.get('expiresAt','?')}" if session.get("id") else f"no session.id \u2014 keys: {list(session.keys())}", d)
        return d
    except Exception as e:
        fail("POST /auth/sign-in/email", str(e))
        return None


def check_session_validation(signin_data: dict) -> None:
    section("4 \u00b7 Session Validation (Bearer token)")
    token = (signin_data.get("session") or {}).get("token")
    if not token:
        warn("GET /auth/get-session", "Skipped \u2014 no token from sign-in")
        return
    try:
        r = requests.get(
            f"{CONFIG['api_base']}/auth/get-session",
            headers={"Authorization": f"Bearer {token}"},
            timeout=10,
        )
        d = r.json() if "application/json" in r.headers.get("content-type", "") else {}
        if r.ok and d.get("user"):
            ok("GET /auth/get-session", f"valid \u2014 email={d['user'].get('email')}", d)
        else:
            fail("GET /auth/get-session", f"HTTP {r.status_code}: {r.text[:200]}", d)
    except Exception as e:
        fail("GET /auth/get-session", str(e))


def check_email_verification(signin_data: dict) -> None:
    section("5 \u00b7 Email Verification")
    verified = (signin_data.get("user") or {}).get("emailVerified")
    if verified:
        ok("emailVerified", str(verified))
    else:
        warn("emailVerified", "false \u2014 blocked if requireEmailVerification=true")


def check_kv() -> None:
    section("6 \u00b7 Better Auth KV")
    success, stdout, stderr = wrangler("kv", "key", "list", "--binding", CONFIG["kv_binding"])
    if not success:
        fail("KV list", (stderr or stdout)[:300])
        return

    # JSON is on stdout; stderr has wrangler warnings (ignored)
    raw = _extract_json(stdout)
    if not raw:
        warn("KV list", f"No JSON found in stdout: {stdout[:200]}")
        return
    try:
        keys = json.loads(raw)
    except json.JSONDecodeError as e:
        warn("KV list", f"JSON parse error: {e} \u2014 raw: {raw[:200]}")
        return
    if not isinstance(keys, list):
        warn("KV list", f"Unexpected type {type(keys)}")
        return

    ok("KV accessible", f"{len(keys)} key(s)")
    if not keys:
        warn("KV key distribution", "0 keys \u2014 normal on fresh deploy")
        return
    prefixes: dict[str, int] = {}
    for k in keys:
        name = k.get("name", "") if isinstance(k, dict) else str(k)
        p = name.split(":")[0] if ":" in name else "other"
        prefixes[p] = prefixes.get(p, 0) + 1
    ok("KV key distribution", "  ".join(f"{p}={c}" for p, c in sorted(prefixes.items())), prefixes)


def check_d1(binding: str, label: str) -> None:
    section(f"7 \u00b7 D1 \u2014 {label}  (binding={binding})")

    success, stdout, stderr = wrangler(
        "d1", "execute", binding, "--remote", "--json",
        "--command", "SELECT name FROM sqlite_master WHERE type='table' ORDER BY name;",
        timeout=60,
    )
    if not success:
        fail(f"D1 {label} execute", (stderr or stdout)[:300])
        return
    ok(f"D1 {label} accessible", "remote query succeeded")

    # Parse JSON output: [{"results": [{"name": "..."}]}]
    tables: list[str] = []
    try:
        raw = _extract_json(stdout)
        if raw:
            data = json.loads(raw)
            for batch in (data if isinstance(data, list) else [data]):
                for row in batch.get("results", []):
                    if "name" in row:
                        tables.append(row["name"])
    except Exception as e:
        warn(f"D1 {label} tables", f"JSON parse error: {e}\n{stdout[:300]}")
        return

    if tables:
        ok(f"D1 {label} tables", f"{len(tables)}: {', '.join(tables)}", {"tables": tables})
    else:
        warn(f"D1 {label} tables", f"No tables parsed. stdout:\n{stdout[:400]}")
        return

    # Row counts for known auth tables
    for tbl in [t for t in ["user", "session", "api_key", "verification", "account"] if t in tables]:
        s2, out2, _ = wrangler(
            "d1", "execute", binding, "--remote", "--json",
            "--command", f"SELECT COUNT(*) as c FROM {tbl};",
            timeout=60,
        )
        if s2:
            try:
                raw2 = _extract_json(out2)
                d2 = json.loads(raw2)
                count = (d2[0] if isinstance(d2, list) else d2)["results"][0].get("c", "?")
                ok(f"D1 {label} \u00b7 {tbl} rows", str(count))
            except Exception:
                pass


def _discover_neon_tables(cur) -> dict[str, str]:
    """
    Query information_schema to find actual table names in the public schema.
    Returns a mapping of logical concept -> actual table name, e.g.:
      {"user": "User", "session": "session", "account": "account", ...}

    Results are cached in ``_neon_table_cache`` so that repeated calls within
    a single healthcheck run do not issue redundant queries.
    """
    global _neon_table_cache
    if _neon_table_cache is not None:
        return _neon_table_cache

    cur.execute("""
        SELECT table_name
        FROM information_schema.tables
        WHERE table_schema = 'public' AND table_type = 'BASE TABLE'
        ORDER BY table_name
    """)
    actual = [row[0] for row in cur.fetchall()]
    console.print(f"[dim]  Neon tables ({len(actual)}): {', '.join(actual)}[/dim]")

    lower_map = {t.lower(): t for t in actual}  # lowercase -> actual
    result: dict[str, str] = {}
    for concept in ["user", "session", "account", "verification"]:
        for candidate in [concept, concept + "s", concept.capitalize(), concept.capitalize() + "s"]:
            if candidate.lower() in lower_map:
                result[concept] = lower_map[candidate.lower()]
                break
    _neon_table_cache = result
    return result


def check_neon(signin_data: dict | None) -> None:
    section("8 \u00b7 Neon / PostgreSQL")
    neon_url = CONFIG["neon_url"]
    if not neon_url:
        warn("Neon connection", "NEON_URL not configured \u2014 set it in tools/auth-healthcheck.env")
        return
    try:
        conn = psycopg2.connect(neon_url, connect_timeout=10)
        conn.autocommit = True
        cur = conn.cursor()
        ok("Neon TCP connection", "connected")
    except Exception as e:
        fail("Neon TCP connection", str(e))
        return

    # Discover actual table names before querying
    try:
        tbl_map = _discover_neon_tables(cur)
    except Exception as e:
        fail("Neon table discovery", str(e))
        cur.close(); conn.close()
        return

    # Row counts
    counts: dict[str, int | str] = {}
    for concept, actual in tbl_map.items():
        try:
            cur.execute(f'SELECT COUNT(*) FROM "{actual}"')
            counts[f"{concept} ({actual})"] = cur.fetchone()[0]  # type: ignore[index]
        except Exception as e:
            counts[f"{concept} ({actual})"] = f"ERROR: {e}"

    has_err = any(str(v).startswith("ERROR") for v in counts.values())
    summary = "  ".join(f"{t}={c}" for t, c in counts.items())
    (fail if has_err else ok)("Neon table counts", summary, counts)

    # Test user row
    user_tbl = tbl_map.get("user")
    if user_tbl:
        try:
            # Try common column name variants
            for name_col in ("displayName", "name"):
                try:
                    cur.execute(
                        f'SELECT id, email, "{name_col}", "emailVerified" FROM "{user_tbl}" WHERE email = %s',
                        (CONFIG["test_email"],),
                    )
                    row = cur.fetchone()
                    if row:
                        ok("Test user in Neon", f"id={row[0]}  {name_col}={row[2]}  verified={row[3]}")
                    else:
                        fail("Test user in Neon", f"{CONFIG['test_email']} not found in \"{user_tbl}\"")
                    break
                except psycopg2.errors.UndefinedColumn:  # type: ignore[attr-defined]
                    conn.rollback()
                    continue
        except Exception as e:
            fail("Test user in Neon", str(e))
    else:
        warn("Test user in Neon", f"No 'user' table found \u2014 discovered: {list(tbl_map.values())}")

    # Session row
    session_tbl = tbl_map.get("session")
    if signin_data and session_tbl:
        session_id = (signin_data.get("session") or {}).get("id")
        if session_id:
            try:
                cur.execute(f'SELECT id FROM "{session_tbl}" WHERE id = %s', (session_id,))
                sess = cur.fetchone()
                if sess:
                    ok("Session in Neon", f"id={str(sess[0])[:20]}\u2026")
                else:
                    warn("Session in Neon", "Not in Postgres \u2014 likely stored in KV only (expected when KV is bound).")
            except Exception as e:
                fail("Session in Neon", str(e))

    cur.close()
    conn.close()


def check_admin_api() -> None:
    section("9 \u00b7 Better Auth Admin API (optional)")
    api_key = CONFIG["better_auth_api_key"]
    if not api_key:
        warn("Admin API", "BETTER_AUTH_API_KEY not set \u2014 skipping")
        return
    try:
        r = requests.get(
            f"{CONFIG['api_base']}/auth/admin/list-users?limit=5",
            headers={"x-api-key": api_key},
            timeout=10,
        )
        ct = r.headers.get("content-type", "")
        if not r.content:
            fail("Admin list-users", f"HTTP {r.status_code} \u2014 empty response body")
            return
        d = r.json() if "application/json" in ct else {}
        if r.ok:
            ok("Admin list-users", f"HTTP {r.status_code} \u2014 {len(d.get('users', []))} user(s)", d)
        elif r.status_code == 401:
            warn("Admin list-users", "HTTP 401 \u2014 check BETTER_AUTH_API_KEY has admin scope (wrangler secret)", d)
        else:
            fail("Admin list-users", f"HTTP {r.status_code}: {r.text[:200]}", d)
    except requests.exceptions.JSONDecodeError as e:
        fail("Admin list-users", f"JSON decode error: {e} \u2014 body: {r.text[:200]}")
    except Exception as e:
        fail("Admin list-users", str(e))


def summarise_tail(lines: list[str]) -> None:
    section("10 \u00b7 Wrangler Tail Summary")
    if not CONFIG["enable_tail"]:
        warn("Tail logs", "disabled (ENABLE_TAIL=false)")
        return
    if not lines:
        warn("Tail log", "no events captured")
        return
    exceptions, error_logs, auth_logs = [], [], []
    for raw in lines:
        raw = raw.strip()
        if not raw:
            continue
        try:
            entry = json.loads(raw)
        except json.JSONDecodeError:
            continue
        if not isinstance(entry, dict):
            continue
        for exc in entry.get("exceptions", []):
            exceptions.append(exc.get("message", str(exc)))
        for log in entry.get("logs", []):
            msg = " ".join(str(p) for p in log.get("message", []))
            lower = msg.lower()
            if any(kw in lower for kw in ("error", "500", "exception")):
                error_logs.append(msg)
            if any(kw in lower for kw in ("auth", "sign-in", "sign-up", "session", "prisma", "better-auth")):
                auth_logs.append(msg)
    (ok if not exceptions else fail)("Worker exceptions",
        f"{len(exceptions)} exception(s)" if exceptions else "none", {"exceptions": exceptions[:10]})
    (ok if not error_logs else warn)("Worker error logs",
        f"{len(error_logs)} line(s)" if error_logs else "none", {"errors": error_logs[:10]})
    (ok if auth_logs else warn)("Auth log events",
        f"{len(auth_logs)} line(s)" if auth_logs else "none captured", {"events": auth_logs[:20]})


def write_report() -> None:
    path = Path(CONFIG["report_file"])
    with open(path, "w") as f:
        json.dump(report, f, indent=2, default=str)
    s = report["summary"]
    console.print()
    console.print(Panel(
        f"[green]\u2705 Passed:   {s['passed']}[/green]\n"
        f"[yellow]\u26a0\ufe0f  Warnings: {s['warnings']}[/yellow]\n"
        f"[red]\u274c Failed:   {s['failed']}[/red]\n"
        f"   Total:    {s['passed'] + s['failed'] + s['warnings']}\n\n"
        f"Report \u2192 [bold]{path.resolve()}[/bold]",
        title="[bold]Auth Healthcheck Complete[/bold]",
    ))
    if report["errors"]:
        console.print("\n[bold red]Failed checks:[/bold red]")
        for e in report["errors"]:
            console.print(f"  \u274c {e['check']}: {e['detail']}")


# ============================================================================
# Cleanup
# ============================================================================

def cleanup_test_user_admin_api() -> bool:
    """Delete the test user via the Better Auth admin API. Returns True if deleted."""
    section("Cleanup \u00b7 Better Auth admin API")
    api_key = CONFIG["better_auth_api_key"]
    if not api_key:
        warn("Admin delete-user (cleanup)", "BETTER_AUTH_API_KEY not set \u2014 skipping")
        return False

    # 1. Locate the user by email
    try:
        r = requests.get(
            f"{CONFIG['api_base']}/auth/admin/list-users",
            headers={"x-api-key": api_key},
            params={"searchField": "email", "searchValue": CONFIG["test_email"]},
            timeout=10,
        )
        if not r.ok:
            warn("Admin find-user (cleanup)", f"HTTP {r.status_code}: {r.text[:200]}")
            return False
        d = r.json() if "application/json" in r.headers.get("content-type", "") else {}
        users = d.get("users", [])
        user_id = next((u["id"] for u in users if u.get("email") == CONFIG["test_email"]), None)
        if not user_id:
            warn("Admin find-user (cleanup)", f"{CONFIG['test_email']} not found \u2014 already deleted?")
            return False
    except Exception as e:
        warn("Admin find-user (cleanup)", str(e))
        return False

    # 2. Delete
    try:
        r = requests.post(
            f"{CONFIG['api_base']}/auth/admin/remove-user",
            headers={"x-api-key": api_key, "Content-Type": "application/json"},
            json={"userId": user_id},
            timeout=10,
        )
        if r.ok:
            ok("Admin delete-user (cleanup)", f"Deleted user_id={user_id}")
            return True
        warn("Admin delete-user (cleanup)", f"HTTP {r.status_code}: {r.text[:200]}")
        return False
    except Exception as e:
        warn("Admin delete-user (cleanup)", str(e))
        return False


def cleanup_test_user_neon() -> bool:
    """Delete the test user row from Neon PostgreSQL. Returns True if a row was removed."""
    section("Cleanup \u00b7 Neon PostgreSQL")
    neon_url = CONFIG["neon_url"]
    if not neon_url:
        warn("Neon delete-user (cleanup)", "NEON_URL not set \u2014 skipping")
        return False
    try:
        conn = psycopg2.connect(neon_url, connect_timeout=10)
        conn.autocommit = True
        cur = conn.cursor()
    except Exception as e:
        warn("Neon connect (cleanup)", str(e))
        return False

    deleted = False
    try:
        tbl_map = _discover_neon_tables(cur)
        user_tbl = tbl_map.get("user")
        if not user_tbl:
            warn("Neon delete-user (cleanup)", f"No user table found \u2014 tables: {list(tbl_map.values())}")
        else:
            # Validate table name before interpolating into the f-string
            if not re.match(_SAFE_TABLE_NAME_RE, user_tbl):
                warn("Neon delete-user (cleanup)", f"Unsafe table name from discovery: {user_tbl!r}")
            else:
                user_id = CONFIG.get("_created_user_id")
                if user_id:
                    cur.execute(f'DELETE FROM "{user_tbl}" WHERE id = %s', (user_id,))
                else:
                    cur.execute(f'DELETE FROM "{user_tbl}" WHERE email = %s', (CONFIG["test_email"],))
                # Only check rowcount when a DELETE was actually executed; cur.rowcount
                # after the table-discovery SELECT may be non-zero and would produce a
                # spurious "Deleted … row(s)" report if we checked it unconditionally.
                if cur.rowcount:
                    ok("Neon delete-user (cleanup)", f"Deleted {cur.rowcount} row(s) from \"{user_tbl}\"")
                    deleted = True
                else:
                    warn("Neon delete-user (cleanup)", f"User not found in \"{user_tbl}\" \u2014 already deleted?")
    except Exception as e:
        warn("Neon delete-user (cleanup)", str(e))
    finally:
        cur.close()
        conn.close()
    return deleted


def cleanup_test_user_d1(binding: str, label: str) -> bool:
    """
    Delete the test user row from a D1 database via ``wrangler d1 execute --remote``.
    Returns True if the command ran without error (row may or may not have existed).

    Security note: ``wrangler d1 execute --command`` does not support parameterised
    queries, so the email is validated against a strict format and then embedded as a
    SQL string literal with single-quote escaping.  The ``user`` table name is
    Better Auth's fixed schema name and is not derived from user input.
    """
    section(f"Cleanup \u00b7 D1 \u2014 {label}  (binding={binding})")
    email = CONFIG["test_email"]
    # Validate the email to a safe subset before constructing the SQL literal.
    if not re.match(r'^[a-zA-Z0-9._%+\-]+@[a-zA-Z0-9.\-]+\.[a-zA-Z]{2,}$', email):
        fail(f"D1 {label} delete-user (cleanup)", f"TEST_EMAIL contains unexpected characters: {email!r}")
        return False
    # Single-quote escaping is the only defence available here; the regex above
    # already excludes backslashes and other shell-relevant characters.
    escaped_email = email.replace("'", "''")
    success, stdout, stderr = wrangler(
        "d1", "execute", binding, "--remote", "--json",
        # "user" is Better Auth's fixed table name, not derived from user input.
        "--command", f"DELETE FROM user WHERE email = '{escaped_email}';",
        timeout=60,
    )
    if success:
        ok(f"D1 {label} delete-user (cleanup)", f"Executed DELETE for {CONFIG['test_email']}")
        return True
    warn(f"D1 {label} delete-user (cleanup)", (stderr or stdout)[:300])
    return False


def cleanup_all_healthcheck_data() -> None:
    """Delete ALL healthcheck-* test data across every data store."""
    console.print()
    console.print(Panel(
        f"[bold yellow]\u26a0\ufe0f  Universal cleanup \u2014 deleting ALL healthcheck-* test data[/bold yellow]\n\n"
        f"   Pattern: email LIKE 'healthcheck-%'\n\n"
        f"   Targets:\n"
        f"     \u00b7 Neon PostgreSQL\n"
        f"     \u00b7 D1 [cyan]{CONFIG['d1_binding']}[/cyan] + D1 [cyan]{CONFIG['d1_admin_binding']}[/cyan]\n"
        f"     \u00b7 Better Auth KV  ([cyan]{CONFIG['kv_binding']}[/cyan])\n"
        f"     \u00b7 Better Auth admin API",
        title="[bold]Universal Cleanup[/bold]",
    ))

    neon_rows: int = 0
    d1_db_rows: int = 0
    d1_admin_rows: int = 0
    kv_keys: int = 0
    api_users: int = 0

    # ── Neon ─────────────────────────────────────────────────────────────────
    section("Universal Cleanup \u00b7 Neon")
    try:
        neon_url = CONFIG.get("neon_url", "")
        if not neon_url:
            console.print("[yellow]\u26a0\ufe0f  NEON_URL not set \u2014 skipping Neon cleanup[/yellow]")
        else:
            conn = psycopg2.connect(neon_url, connect_timeout=10)
            conn.autocommit = True
            cur = conn.cursor()
            try:
                tbl_map = _discover_neon_tables(cur)
                user_tbl = tbl_map.get("user")
                if not user_tbl:
                    console.print(f"[yellow]\u26a0\ufe0f  No user table found \u2014 tables: {list(tbl_map.values())}[/yellow]")
                else:
                    if not re.match(_SAFE_TABLE_NAME_RE, user_tbl):
                        console.print(f"[yellow]\u26a0\ufe0f  Unsafe user table name: {user_tbl!r}[/yellow]")
                    else:
                        # Collect healthcheck user IDs before deleting so we can
                        # cascade-delete related orphan rows in session / account.
                        cur.execute(
                            psycopg2.sql.SQL(
                                "SELECT id FROM {} WHERE email LIKE 'healthcheck-%'"
                            ).format(psycopg2.sql.Identifier(user_tbl))
                        )
                        hc_user_ids = [row[0] for row in cur.fetchall()]

                        # Orphan cleanup: session and account rows whose userId
                        # belongs to a healthcheck user.
                        for orphan_concept in ("session", "account"):
                            orphan_tbl = tbl_map.get(orphan_concept)
                            if not orphan_tbl:
                                continue
                            if not re.match(_SAFE_TABLE_NAME_RE, orphan_tbl):
                                console.print(
                                    f"[yellow]\u26a0\ufe0f  Unsafe {orphan_concept} table name: {orphan_tbl!r}[/yellow]"
                                )
                                continue
                            if not hc_user_ids:
                                continue
                            try:
                                cur.execute(
                                    psycopg2.sql.SQL(
                                        "DELETE FROM {} WHERE {} = ANY(%s)"
                                    ).format(
                                        psycopg2.sql.Identifier(orphan_tbl),
                                        psycopg2.sql.Identifier("userId"),
                                    ),
                                    (hc_user_ids,),
                                )
                                neon_rows += cur.rowcount
                                console.print(
                                    f"[dim]  \u00b7 Deleted {cur.rowcount} orphan row(s) from \"{orphan_tbl}\"[/dim]"
                                )
                            except Exception as e_orphan:
                                console.print(
                                    f"[yellow]\u26a0\ufe0f  Orphan cleanup failed for \"{orphan_tbl}\": {e_orphan}[/yellow]"
                                )

                        # Verification table: delete rows by identifier pattern.
                        verif_tbl = tbl_map.get("verification")
                        if verif_tbl:
                            if not re.match(_SAFE_TABLE_NAME_RE, verif_tbl):
                                console.print(
                                    f"[yellow]\u26a0\ufe0f  Unsafe verification table name: {verif_tbl!r}[/yellow]"
                                )
                            else:
                                try:
                                    cur.execute(
                                        psycopg2.sql.SQL(
                                            "DELETE FROM {} WHERE {} LIKE 'healthcheck-%'"
                                        ).format(
                                            psycopg2.sql.Identifier(verif_tbl),
                                            psycopg2.sql.Identifier("identifier"),
                                        )
                                    )
                                    neon_rows += cur.rowcount
                                    console.print(
                                        f"[dim]  \u00b7 Deleted {cur.rowcount} row(s) from \"{verif_tbl}\"[/dim]"
                                    )
                                except Exception as e_verif:
                                    console.print(
                                        f"[yellow]\u26a0\ufe0f  Verification cleanup failed: {e_verif}[/yellow]"
                                    )

                        # Delete the healthcheck user rows themselves.
                        cur.execute(
                            psycopg2.sql.SQL(
                                "DELETE FROM {} WHERE email LIKE 'healthcheck-%'"
                            ).format(psycopg2.sql.Identifier(user_tbl))
                        )
                        neon_rows += cur.rowcount
                        console.print(
                            f"[dim]  \u00b7 Deleted {cur.rowcount} user row(s) from \"{user_tbl}\"[/dim]"
                        )
            finally:
                cur.close()
                conn.close()
    except Exception as e:
        console.print(f"[yellow]\u26a0\ufe0f  Neon cleanup failed: {e}[/yellow]")

    # ── D1 DB ────────────────────────────────────────────────────────────────
    section("Universal Cleanup \u00b7 D1 DB")
    try:
        binding = CONFIG["d1_binding"]
        success, stdout, stderr = wrangler(
            "d1", "execute", binding, "--remote", "--json",
            "--command", "DELETE FROM user WHERE email LIKE 'healthcheck-%';",
            timeout=60,
        )
        if success:
            raw = _extract_json(stdout)
            if raw:
                try:
                    data = json.loads(raw)
                    if isinstance(data, list):
                        for entry in data:
                            if isinstance(entry, dict):
                                d1_db_rows += entry.get("meta", {}).get("changes", 0)
                except json.JSONDecodeError as e_json:
                    console.print(
                        f"[yellow]\u26a0\ufe0f  D1 {binding}: could not parse result JSON: {e_json}[/yellow]"
                    )
            else:
                console.print(f"[yellow]\u26a0\ufe0f  D1 {binding}: no JSON in wrangler output[/yellow]")
            console.print(f"[dim]  \u00b7 D1 {binding}: {d1_db_rows} row(s) deleted[/dim]")
        else:
            console.print(
                f"[yellow]\u26a0\ufe0f  D1 {binding} cleanup failed: {(stderr or stdout)[:300]}[/yellow]"
            )
    except Exception as e:
        console.print(f"[yellow]\u26a0\ufe0f  D1 DB cleanup failed: {e}[/yellow]")

    # ── D1 ADMIN_DB ──────────────────────────────────────────────────────────
    section("Universal Cleanup \u00b7 D1 ADMIN_DB")
    try:
        binding = CONFIG["d1_admin_binding"]
        success, stdout, stderr = wrangler(
            "d1", "execute", binding, "--remote", "--json",
            "--command", "DELETE FROM user WHERE email LIKE 'healthcheck-%';",
            timeout=60,
        )
        if success:
            raw = _extract_json(stdout)
            if raw:
                try:
                    data = json.loads(raw)
                    if isinstance(data, list):
                        for entry in data:
                            if isinstance(entry, dict):
                                d1_admin_rows += entry.get("meta", {}).get("changes", 0)
                except json.JSONDecodeError as e_json:
                    console.print(
                        f"[yellow]\u26a0\ufe0f  D1 {binding}: could not parse result JSON: {e_json}[/yellow]"
                    )
            else:
                console.print(f"[yellow]\u26a0\ufe0f  D1 {binding}: no JSON in wrangler output[/yellow]")
            console.print(f"[dim]  \u00b7 D1 {binding}: {d1_admin_rows} row(s) deleted[/dim]")
        else:
            console.print(
                f"[yellow]\u26a0\ufe0f  D1 {binding} cleanup failed: {(stderr or stdout)[:300]}[/yellow]"
            )
    except Exception as e:
        console.print(f"[yellow]\u26a0\ufe0f  D1 ADMIN_DB cleanup failed: {e}[/yellow]")

    # ── KV ───────────────────────────────────────────────────────────────────
    section("Universal Cleanup \u00b7 KV")
    try:
        kv_binding = CONFIG["kv_binding"]
        success, stdout, stderr = wrangler("kv", "key", "list", "--binding", kv_binding)
        if not success:
            console.print(
                f"[yellow]\u26a0\ufe0f  KV list failed: {(stderr or stdout)[:300]}[/yellow]"
            )
        else:
            raw = _extract_json(stdout)
            if raw:
                keys = json.loads(raw)
                if isinstance(keys, list):
                    hc_key_names = [
                        k.get("name", "")
                        for k in keys
                        if isinstance(k, dict) and "healthcheck-" in k.get("name", "")
                    ]
                    for key_name in hc_key_names:
                        del_ok, _, _ = wrangler(
                            "kv", "key", "delete", "--binding", kv_binding, key_name
                        )
                        if del_ok:
                            kv_keys += 1
                    console.print(f"[dim]  \u00b7 KV: deleted {kv_keys} key(s)[/dim]")
    except Exception as e:
        console.print(f"[yellow]\u26a0\ufe0f  KV cleanup failed: {e}[/yellow]")

    # ── Admin API ────────────────────────────────────────────────────────────
    section("Universal Cleanup \u00b7 Admin API")
    try:
        api_key = CONFIG.get("better_auth_api_key", "")
        if not api_key:
            console.print(
                "[yellow]\u26a0\ufe0f  BETTER_AUTH_API_KEY not set \u2014 skipping Admin API cleanup[/yellow]"
            )
        else:
            r = requests.get(
                f"{CONFIG['api_base']}/auth/admin/list-users",
                params={"searchField": "email", "searchValue": "healthcheck-"},
                headers={"x-api-key": api_key},
                timeout=10,
            )
            if r.ok:
                d = r.json() if "application/json" in r.headers.get("content-type", "") else {}
                users = d.get("users", [])
                # Client-side filter as a defense-in-depth guard: the API
                # searchValue parameter performs a substring match that may
                # return partial results; re-filter to ensure only genuine
                # healthcheck accounts are deleted.
                hc_users = [u for u in users if "healthcheck-" in u.get("email", "")]
                for u in hc_users:
                    try:
                        del_r = requests.post(
                            f"{CONFIG['api_base']}/auth/admin/remove-user",
                            headers={"x-api-key": api_key, "Content-Type": "application/json"},
                            json={"userId": u["id"]},
                            timeout=10,
                        )
                        if del_r.ok:
                            api_users += 1
                    except Exception as e_del:
                        console.print(
                            f"[yellow]\u26a0\ufe0f  Admin API delete user {u.get('id')} failed: {e_del}[/yellow]"
                        )
                console.print(f"[dim]  \u00b7 Admin API: deleted {api_users} user(s)[/dim]")
            else:
                console.print(
                    f"[yellow]\u26a0\ufe0f  Admin API list-users failed: HTTP {r.status_code}[/yellow]"
                )
    except Exception as e:
        console.print(f"[yellow]\u26a0\ufe0f  Admin API cleanup failed: {e}[/yellow]")

    # ── Summary ───────────────────────────────────────────────────────────────
    console.print(
        f"\n[bold]Cleanup summary:[/bold] Cleaned {neon_rows} Neon rows, "
        f"{d1_db_rows} D1-DB rows, {d1_admin_rows} D1-ADMIN rows, "
        f"{kv_keys} KV keys, {api_users} admin API users"
    )


def run_cleanup() -> None:
    """Orchestrate all cleanup tasks: remove the test user from every data store."""
    console.print()
    console.print(Panel(
        f"[bold yellow]\u26a0\ufe0f  Deleting test data[/bold yellow]\n\n"
        f"   Email : [cyan]{CONFIG['test_email']}[/cyan]\n\n"
        f"   Targets:\n"
        f"     \u00b7 Better Auth admin API  (POST /auth/admin/remove-user)\n"
        f"     \u00b7 Neon PostgreSQL        (DELETE FROM user WHERE email = \u2026)\n"
        f"     \u00b7 D1 [cyan]{CONFIG['d1_binding']}[/cyan]       (DELETE FROM user WHERE email = \u2026)\n"
        f"     \u00b7 D1 [cyan]{CONFIG['d1_admin_binding']}[/cyan]  (DELETE FROM user WHERE email = \u2026)",
        title="[bold]Cleanup[/bold]",
    ))
    cleanup_test_user_admin_api()
    cleanup_test_user_neon()
    cleanup_test_user_d1(CONFIG["d1_binding"],     "adblock-compiler-d1-database")
    cleanup_test_user_d1(CONFIG["d1_admin_binding"], "adblock-compiler-admin-d1")


# ============================================================================
# Interactive menu
# ============================================================================

def _show_menu() -> tuple[str, bool]:
    """
    Render an interactive action menu when stdin is a TTY.
    Returns ``(mode, dry_run)`` where mode is one of:
      ``"checks"`` | ``"checks-cleanup"`` | ``"cleanup"`` | ``"quit"``
    and ``dry_run`` is True when the user chose the read-only option.
    """
    from rich.prompt import Prompt

    console.print()
    console.print(Panel(
        "  [bold]1[/bold]  Run all checks  (no cleanup)\n"
        "  [bold]2[/bold]  Run all checks, then clean up test data\n"
        "  [bold]3[/bold]  Dry-run  (read-only checks \u2014 no sign-up / sign-in, no cleanup)\n"
        "  [bold]4[/bold]  Clean up ALL healthcheck test data (any run)\n"
        "  [bold]q[/bold]  Quit",
        title="[bold cyan]adblock-compiler \u00b7 Auth Healthcheck[/bold cyan]",
        subtitle="Select an action",
    ))
    choice = Prompt.ask("Action", choices=["1", "2", "3", "4", "q"], default="1")
    return {
        "1": ("checks",          False),
        "2": ("checks-cleanup",  False),
        "3": ("checks",          True),   # dry-run
        "4": ("cleanup",         False),
        "q": ("quit",            False),
    }[choice]


# ============================================================================
# Entry point
# ============================================================================

def main() -> None:
    global CONFIG
    parser = argparse.ArgumentParser(
        description="Better Auth production healthcheck",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Modes\n"
            "  all             Run all checks  (default in pipelines / CI)\n"
            "  checks          Run checks only \u2014 do not clean up test data\n"
            "  cleanup         Delete test data only \u2014 skip checks\n"
            "  checks-cleanup  Run checks then delete test data\n\n"
            "When stdin is a TTY and --mode is not given, an interactive menu is shown.\n\n"
            "Exit codes\n"
            "  0   All checks passed (or cleanup-only with no errors)\n"
            "  1   One or more checks FAILED\n"
        ),
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Skip all write operations (sign-up, sign-in); read-only checks only (also suppresses cleanup)",
    )
    parser.add_argument(
        "--mode",
        choices=["all", "checks", "cleanup", "checks-cleanup"],
        default=None,
        help="Action to perform; omit to show an interactive menu when stdin is a TTY, else 'all'",
    )
    parser.add_argument(
        "--cleanup", action="store_true",
        help="Shorthand for --mode checks-cleanup: run checks then clean up test data",
    )
    args = parser.parse_args()

    CONFIG = _load_config()
    CONFIG["dry_run"] = args.dry_run
    report["api_base"] = CONFIG["api_base"]

    console.print(Panel(
        f"[bold cyan]Better Auth Production Healthcheck[/bold cyan]\n"
        f"API base : {CONFIG['api_base']}\n"
        f"Test user: {CONFIG['test_email']}\n"
        f"Repo root: {CONFIG['repo_root']}\n"
        f"Logs dir : {CONFIG['logs_dir']}\n"
        f"Dry-run  : {CONFIG['dry_run']}\n"
        f"Time     : {datetime.now().isoformat()}",
        title="adblock-compiler \u00b7 bloqr.dev",
    ))

    # ── Determine mode ───────────────────────────────────────────────────────
    if args.cleanup and not args.mode:
        mode = "checks-cleanup"
    elif args.mode:
        mode = args.mode
    elif sys.stdin.isatty():
        mode, dry_run_override = _show_menu()
        if mode == "quit":
            sys.exit(0)
        if dry_run_override:
            CONFIG["dry_run"] = True
    else:
        mode = "all"   # pipeline / CI default

    # dry-run always suppresses per-run cleanup to avoid accidental deletes
    do_checks = mode in ("all", "checks", "checks-cleanup")
    do_per_run_cleanup = mode in ("all", "checks-cleanup") and not CONFIG["dry_run"]
    do_universal_cleanup = mode == "cleanup" and not CONFIG["dry_run"]

    # ── Run ──────────────────────────────────────────────────────────────────
    start_tail()
    time.sleep(1)

    signin_data: dict | None = None
    try:
        if do_checks:
            check_api()
            signup_result = check_signup()
            signin_data = check_signin(signup_result, signup_succeeded=signup_result is not None)

            if signin_data:
                check_session_validation(signin_data)
                check_email_verification(signin_data)
            else:
                warn("Session + email checks", "Skipped \u2014 sign-in failed")

            check_kv()
            check_d1(CONFIG["d1_binding"],      "adblock-compiler-d1-database")
            check_d1(CONFIG["d1_admin_binding"], "adblock-compiler-admin-d1")
            check_neon(signin_data)
            check_admin_api()

            if CONFIG["enable_tail"]:
                console.print(f"\n[dim]Waiting {CONFIG['tail_wait_sec']}s for tail to flush\u2026[/dim]")
                time.sleep(CONFIG["tail_wait_sec"])

        if do_per_run_cleanup:
            run_cleanup()
        elif do_universal_cleanup:
            cleanup_all_healthcheck_data()

    finally:
        stop_tail()
        try:
            tail_log = Path(CONFIG["tail_log_file"])
            tail_lines = tail_log.read_text(encoding="utf-8").splitlines() if tail_log.exists() else []
        except Exception as exc:
            console.print(f"[yellow]⚠️  Could not read tail log: {exc}[/yellow]")
            tail_lines = []
        try:
            summarise_tail(tail_lines)
        except Exception as e:
            console.print(f"[yellow]⚠️  summarise_tail error: {e}[/yellow]")
        write_report()

    if report["summary"]["failed"] > 0:
        sys.exit(1)


if __name__ == "__main__":
    main()
