name = "bloqr-docs-starlight"
compatibility_date = "2026-01-01"

[[routes]]
pattern = "docs-v3.bloqr.dev"
custom_domain = true

[assets]
directory = "./dist"
html_handling = "auto-trailing-slash"
not_found_handling = "404-page"
